import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { isOwnerTelegramId } from "@/lib/owner";
import { validateTelegramInitData } from "@/lib/telegram-initdata";
export type TelegramGateChatType="channel"|"group"|"supergroup";
export type TelegramGateChat={id:string;type:TelegramGateChatType;url:string;name:string;username?:string|null;description?:string|null;memberCount?:number|null;verified?:boolean};
export type TelegramGateSettings={enabled:boolean;chatType:TelegramGateChatType;channelId:string;channelUrl:string;channelName:string;title:string;description:string;joinButtonText:string;checkButtonText:string;successMessage:string;failureMessage:string;checkIntervalSeconds:number;revokeOnLeave:boolean;allowAdmins:boolean;allowCreators:boolean;allowMembers:boolean;allowRestricted:boolean;requiredChats:TelegramGateChat[]};
const DEFAULTS:TelegramGateSettings={enabled:false,chatType:"channel",channelId:"",channelUrl:"",channelName:"TASKORA Community",title:"JOIN TASKORA COMMUNITY",description:"Join every required TASKORA Telegram community to unlock the Mini App.",joinButtonText:"JOIN TELEGRAM",checkButtonText:"CHECK MEMBERSHIP",successMessage:"Your TASKORA access has been unlocked.",failureMessage:"Join every required TASKORA Telegram community and try again.",checkIntervalSeconds:30,revokeOnLeave:true,allowAdmins:true,allowCreators:true,allowMembers:true,allowRestricted:false,requiredChats:[]};
async function adminClient(){const{supabaseAdmin}=await import("@/integrations/supabase/client.server");return supabaseAdmin}
async function assertOwner(userId:string){const s=await adminClient();const{data:role}=await s.rpc("has_role",{_user_id:userId,_role:"admin"});if(role)return;const{data:p}=await s.from("profiles").select("telegram_id").eq("id",userId).maybeSingle();if(isOwnerTelegramId((p as any)?.telegram_id??null))return;throw new Error("Owner/admin authorization required.")}
function chatType(v:unknown):TelegramGateChatType{const s=String(v??"channel").toLowerCase();return s==="group"||s==="supergroup"?s:"channel"}
function normalizeChats(v:unknown):TelegramGateChat[]{if(!Array.isArray(v))return[];return v.map((x:any)=>({id:String(x?.id??"").trim(),type:chatType(x?.type),url:String(x?.url??"").trim(),name:String(x?.name??x?.title??"").trim(),username:x?.username?String(x.username):null,description:x?.description?String(x.description):null,memberCount:x?.memberCount==null?null:Number(x.memberCount),verified:Boolean(x?.verified)})).filter(x=>x.id)}
function normalize(row:any):TelegramGateSettings{let list=normalizeChats(row?.required_chats);if(!list.length&&row?.channel_id)list=[{id:String(row.channel_id),type:chatType(row.chat_type),url:String(row.channel_url??""),name:String(row.channel_name??DEFAULTS.channelName)}];return{...DEFAULTS,enabled:Boolean(row?.enabled),chatType:chatType(row?.chat_type),channelId:String(row?.channel_id??""),channelUrl:String(row?.channel_url??""),channelName:String(row?.channel_name??DEFAULTS.channelName),title:String(row?.title??DEFAULTS.title),description:String(row?.description??DEFAULTS.description),joinButtonText:String(row?.join_button_text??DEFAULTS.joinButtonText),checkButtonText:String(row?.check_button_text??DEFAULTS.checkButtonText),successMessage:String(row?.success_message??DEFAULTS.successMessage),failureMessage:String(row?.failure_message??DEFAULTS.failureMessage),checkIntervalSeconds:Math.min(300,Math.max(15,Number(row?.check_interval_seconds??30))),revokeOnLeave:true,requiredChats:list}}
async function readSettings(){try{const s=await adminClient();const{data,error}=await(s as any).from("telegram_gate_settings").select("*").eq("id",true).maybeSingle();if(error)return DEFAULTS;return normalize(data)}catch{return DEFAULTS}}
async function logEvent(x:{userId:string;telegramId:number;status:"verified"|"not_member"|"error";membershipStatus?:string|null;errorCode?:string|null}){try{const s=await adminClient();await(s as any).from("telegram_gate_events").insert({user_id:x.userId,telegram_id:x.telegramId,status:x.status,membership_status:x.membershipStatus??null,error_code:x.errorCode??null})}catch{}}
async function tg(token:string,method:string,body:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});return{httpOk:r.ok,...await r.json() as any}}
export const getTelegramGateSettings=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await assertOwner(context.userId);return readSettings()});
export const saveTelegramGateSettings=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:TelegramGateSettings)=>data).handler(async({data,context})=>{await assertOwner(context.userId);const s=await adminClient();const list=normalizeChats(data.requiredChats);if(!list.length&&data.channelId.trim())list=[{id:data.channelId.trim(),type:chatType(data.chatType),url:data.channelUrl.trim(),name:data.channelName.trim()||DEFAULTS.channelName}];if(data.enabled&&!list.length)throw new Error("Add at least one Telegram channel or group before enabling the gate.");const first=list[0];const payload={id:true,enabled:Boolean(data.enabled),chat_type:first?.type??"channel",channel_id:first?.id??null,channel_url:first?.url??null,channel_name:first?.name??DEFAULTS.channelName,title:data.title.trim()||DEFAULTS.title,description:data.description.trim()||DEFAULTS.description,join_button_text:data.joinButtonText.trim()||DEFAULTS.joinButtonText,check_button_text:data.checkButtonText.trim()||DEFAULTS.checkButtonText,success_message:data.successMessage.trim()||DEFAULTS.successMessage,failure_message:data.failureMessage.trim()||DEFAULTS.failureMessage,check_interval_seconds:Math.min(300,Math.max(15,Math.floor(Number(data.checkIntervalSeconds)||30))),revoke_on_leave:true,allow_admins:true,allow_creators:true,allow_members:true,allow_restricted:false,required_chats:list,updated_by:context.userId,updated_at:new Date().toISOString()};const{error}=await(s as any).from("telegram_gate_settings").upsert(payload,{onConflict:"id"});if(error)throw new Error(error.message);return normalize(payload)});
export const previewTelegramGateChats=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{chats:TelegramGateChat[]})=>data).handler(async({data,context})=>{await assertOwner(context.userId);const token=process.env.TELEGRAM_BOT_TOKEN??"";if(!token)throw new Error("TELEGRAM_BOT_TOKEN is not configured on the server.");const out:TelegramGateChat[]=[];for(const item of normalizeChats(data.chats)){const r=await tg(token,"getChat",{chat_id:item.id});if(!r.ok){out.push({...item,verified:false});continue}let memberCount:number|null=null;try{const c=await tg(token,"getChatMemberCount",{chat_id:item.id});if(c.ok)memberCount=Number(c.result)}catch{}const c=r.result??{};out.push({id:String(c.id??item.id),type:chatType(c.type),url:item.url||c.invite_link||(c.username?`https://t.me/${c.username}`:""),name:String(c.title??c.username??item.name),username:c.username?String(c.username):null,description:c.description?String(c.description):null,memberCount,verified:true})}return out});
export const testTelegramGateConnection=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await assertOwner(context.userId);const s=await readSettings();const token=process.env.TELEGRAM_BOT_TOKEN??"";if(!token)return{ok:false as const,error:"TELEGRAM_BOT_TOKEN is not configured on the server."};const me=await tg(token,"getMe",{});if(!me.ok)return{ok:false as const,error:me.description??"Bot token rejected by Telegram."};const result=await previewTelegramGateChats({data:{chats:s.requiredChats}});const failed=result.filter(x=>!x.verified);return{ok:result.length>0&&failed.length===0,botUsername:me.result?.username??null,channelTitle:result[0]?.name??s.channelName,channelType:result[0]?.type??s.chatType,chats:result,error:failed.length?`${failed.length} required chat(s) could not be read. Add the bot as administrator and check the chat IDs.`:undefined}});
export const getTelegramGateAnalytics=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await assertOwner(context.userId);try{const s=await adminClient();const{data}=await(s as any).from("telegram_gate_events").select("status,checked_at").order("checked_at",{ascending:false}).limit(500);const rows=(data??[])as any[];const verified=rows.filter(r=>r.status==="verified").length;const notMember=rows.filter(r=>r.status==="not_member").length;const failed=rows.filter(r=>r.status==="error").length;const total=rows.length;return{total,verified,notMember,failed,successRate:total?Math.round(verified/total*100):0,lastVerified:rows.find(r=>r.status==="verified")?.checked_at??null,lastFailed:rows.find(r=>r.status!=="verified")?.checked_at??null,recent:rows.slice(0,12)}}catch{return{total:0,verified:0,notMember:0,failed:0,successRate:0,lastVerified:null,lastFailed:null,recent:[]}}});
export const getTelegramGateStatus=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{initData:string;force?:boolean})=>data).handler(async({data,context})=>{const settings=await readSettings();if(!settings.enabled)return{allowed:true as const,configured:false as const,settings};const token=process.env.TELEGRAM_BOT_TOKEN??"";if(!token||!settings.requiredChats.length)return{allowed:false as const,configured:false as const,temporaryError:"Telegram Gate is not configured yet. Please contact TASKORA support.",settings};const validated=await validateTelegramInitData(data.initData,token);const telegramId=validated.user.id;const s=await adminClient();const{data:profile}=await s.from("profiles").select("telegram_id").eq("id",context.userId).maybeSingle();if(Number((profile as any)?.telegram_id??0)!==telegramId)throw new Error("Telegram identity mismatch. Re-open TASKORA from Telegram.");const results:any[]=[];for(const chat of settings.requiredChats){try{const p=await tg(token,"getChatMember",{chat_id:chat.id,user_id:telegramId});if(!p.ok||!p.result?.status){results.push({chat,status:"error",allowed:false});continue}const status=String(p.result.status);const allowed=status==="creator"||status==="administrator"||status==="member"||(status==="restricted"&&p.result.is_member===true);results.push({chat,status,allowed})}catch{results.push({chat,status:"error",allowed:false})}}const denied=results.find(x=>!x.allowed&&x.status!=="error");const transient=results.some(x=>x.status==="error");if(denied){await logEvent({userId:context.userId,telegramId,status:"not_member",membershipStatus:denied.status,errorCode:denied.chat.id});return{allowed:false as const,configured:true as const,settings,failedChat:denied.chat,membershipStatus:denied.status}}if(transient){await logEvent({userId:context.userId,telegramId,status:"error",errorCode:"telegram_membership_check_failed"});return{allowed:false as const,configured:true as const,temporaryError:"Telegram membership verification is temporarily unavailable. Please try again.",settings}}await logEvent({userId:context.userId,telegramId,status:"verified",membershipStatus:"member"});return{allowed:true as const,configured:true as const,settings,checkedChats:results.map(x=>({id:x.chat.id,status:x.status}))}});
