import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { isOwnerTelegramId } from "@/lib/owner";

async function adminClient() { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); return supabaseAdmin; }
async function assertOwner(userId: string) { const s = await adminClient(); const { data: role } = await s.rpc("has_role", { _user_id: userId, _role: "admin" }); if (role) return; const { data: p } = await s.from("profiles").select("telegram_id").eq("id", userId).maybeSingle(); if (isOwnerTelegramId((p as any)?.telegram_id ?? null)) return; throw new Error("Owner/admin authorization required."); }

export type WatchVideo = { id:string; title:string; description:string|null; thumbnailUrl:string|null; videoUrl:string|null; sourceType:"owner_uploaded"|"external_provider"; providerName:string|null; providerVideoId:string|null; rewardUsdt:number; rewardPoints:number; durationSeconds:number; status:string };
function mapVideo(row: Record<string, unknown>): WatchVideo { return { id:String(row.id), title:String(row.title), description:(row.description as string|null)??null, thumbnailUrl:(row.thumbnail_url as string|null)??null, videoUrl:(row.video_url as string|null)??null, sourceType:row.source_type === "external_provider" ? "external_provider" : "owner_uploaded", providerName:(row.provider_name as string|null)??null, providerVideoId:(row.provider_video_id as string|null)??null, rewardUsdt:Number(row.reward_usdt??0), rewardPoints:Number(row.reward_points??0), durationSeconds:Number(row.duration_seconds??0), status:String(row.status??"active") }; }

export const listWatchVideos = createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async()=>{ const s=await adminClient(); const {data,error}=await (s as any).from("watch_videos").select("id,title,description,thumbnail_url,video_url,source_type,provider_name,provider_video_id,reward_usdt,reward_points,duration_seconds,status").eq("status","active").order("created_at",{ascending:false}).limit(50); if(error) throw new Error(error.message); return ((data??[]) as Record<string,unknown>[]).map(mapVideo); });
export const startWatchVideo = createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{videoId:string})=>data).handler(async({data,context})=>{ const s=await adminClient(); const {data:v}=await (s as any).from("watch_videos").select("id,status,source_type,duration_seconds,reward_usdt,reward_points,max_views,views_count").eq("id",data.videoId).eq("status","active").maybeSingle(); if(!v) throw new Error("This video is no longer available."); if(v.max_views!=null&&Number(v.views_count)>=Number(v.max_views)) throw new Error("This video has reached its view limit."); const {data:e}=await (s as any).from("watch_video_sessions").select("id,status").eq("video_id",data.videoId).eq("user_id",context.userId).eq("status","started").maybeSingle(); if(e)return{sessionId:String(e.id),sourceType:String(v.source_type)}; const {data:session,error}=await (s as any).from("watch_video_sessions").insert({video_id:data.videoId,user_id:context.userId}).select("id").single(); if(error||!session)throw new Error(error?.message??"Could not start video session."); return{sessionId:String(session.id),sourceType:String(v.source_type)}; });
export const completeWatchVideo = createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{sessionId:string})=>data).handler(async({data,context})=>{ const s=await adminClient(); const {data:session}=await (s as any).from("watch_video_sessions").select("id,video_id,user_id,started_at,status").eq("id",data.sessionId).eq("user_id",context.userId).maybeSingle(); if(!session)throw new Error("Video session not found."); if(session.status==="completed")return{ok:true as const,already:true as const}; if(session.status!=="started")throw new Error("This video session is no longer valid."); const {data:v}=await (s as any).from("watch_videos").select("id,source_type,duration_seconds,reward_usdt,reward_points,title,views_count").eq("id",session.video_id).maybeSingle(); if(!v)throw new Error("Video not found."); if(v.source_type==="external_provider")throw new Error("External-provider rewards are credited only after the provider verifies the completion."); const elapsed=(Date.now()-new Date(String(session.started_at)).getTime())/1000; const required=Math.max(3,Number(v.duration_seconds||0)); if(elapsed+1<required)throw new Error(`Keep watching for ${Math.ceil(required-elapsed)} more seconds.`); const {data:updated,error:updateError}=await (s as any).from("watch_video_sessions").update({status:"completed",completed_at:new Date().toISOString(),reward_usdt:Number(v.reward_usdt??0),reward_points:Number(v.reward_points??0)}).eq("id",session.id).eq("status","started").select("id").maybeSingle(); if(updateError)throw new Error(updateError.message); if(!updated)return{ok:true as const,already:true as const}; const rewardUsdt=Number(v.reward_usdt??0),rewardPoints=Number(v.reward_points??0); if(rewardUsdt>0){const {error}=await s.from("transactions").insert({user_id:context.userId,label:`Watch video — ${String(v.title)}`,amount:rewardUsdt,kind:"reward"});if(error)throw new Error(error.message);} if(rewardPoints>0){const {data:p}=await s.from("profiles").select("xp").eq("id",context.userId).maybeSingle();await(s as any).from("profiles").update({xp:Number(p?.xp??0)+rewardPoints}).eq("id",context.userId);} await(s as any).from("watch_videos").update({views_count:Number(v.views_count??0)+1}).eq("id",v.id); return{ok:true as const,already:false as const,rewardUsdt,rewardPoints}; });

export const registerOwnerVideo = createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{title:string;description?:string;videoUrl:string;platform:string;rewardUsdt:number;rewardPoints:number;durationSeconds?:number;thumbnailUrl?:string})=>data).handler(async({data,context})=>{ await assertOwner(context.userId); if(!data.title.trim())throw new Error("Video title is required."); if(!/^https?:\/\//i.test(data.videoUrl.trim()))throw new Error("Enter a valid video link."); if(data.rewardUsdt<0||data.rewardPoints<0)throw new Error("Rewards cannot be negative."); const platform=data.platform.trim(); if(!platform)throw new Error("Choose a platform."); const s=await adminClient(); const {data:row,error}=await(s as any).from("watch_videos").insert({title:data.title.trim(),description:data.description?.trim()||null,video_url:data.videoUrl.trim(),thumbnail_url:data.thumbnailUrl?.trim()||null,source_type:"external_provider",provider_name:platform,provider_video_id:data.videoUrl.trim(),reward_usdt:data.rewardUsdt,reward_points:data.rewardPoints,duration_seconds:Math.max(0,Math.round(data.durationSeconds??0)),status:"active",created_by:context.userId}).select("*").single(); if(error)throw new Error(error.message); return mapVideo(row as Record<string,unknown>); });
export const listOwnerVideos=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await assertOwner(context.userId);const s=await adminClient();const{data,error}=await(s as any).from("watch_videos").select("*").order("created_at",{ascending:false}).limit(100);if(error)throw new Error(error.message);return((data??[])as Record<string,unknown>[]).map(mapVideo);});
