import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Bell, ChevronRight, Link2, Shield, CheckCircle2, Copy, Gamepad2 } from "lucide-react";
import { beginDiscordConnect, getConnectedVerificationInfo, listConnectedAccounts, verifyPublicProfile, verifyYouTubeChannel } from "@/lib/connected-accounts.functions";
import { CONNECTABLE_PLATFORMS } from "@/lib/taskora-data";
import { PlatformLogo, platformLabel, type Platform } from "@/components/PlatformIcon";
import { TASKORA_LOGO } from "@/lib/brand";

export const Route=createFileRoute("/_authenticated/connected")({loader:async()=>{const [accounts,verification]=await Promise.all([listConnectedAccounts().catch(()=>[]),getConnectedVerificationInfo().catch(()=>({referralLink:"",message:""}))]);return{accounts,verification};},head:()=>({meta:[{title:"Connected — TASKORA"}]}),component:ConnectedPage});
function ConnectedPage(){
 const initial=Route.useLoaderData(); const [platform,setPlatform]=useState<Platform>("youtube"); const [value,setValue]=useState(""); const [msg,setMsg]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [copied,setCopied]=useState(false); const [list,setList]=useState<any[]>(initial.accounts.filter((a:any)=>a.platform!=="telegram"));
 const verify=async()=>{setBusy(true);setMsg(null);try{const row=platform==="youtube"?await verifyYouTubeChannel({data:{channelUrl:value}}):await verifyPublicProfile({data:{platform,profileUrl:value}});setList(p=>[row,...p.filter(a=>a.platform!==platform)]);setValue("");setMsg("Account verified and connected.");}catch(e){setMsg(e instanceof Error?e.message:"Verification failed.");}finally{setBusy(false);}};
 const discord=async()=>{setBusy(true);setMsg(null);try{const r=await beginDiscordConnect();window.location.assign(r.url);}catch(e){setMsg(e instanceof Error?e.message:"Discord connection failed.");setBusy(false);}};
 return <main className="mx-auto min-h-screen w-full max-w-md px-3.5 pb-28 pt-3 text-white">
 <header className="mb-4 flex items-center gap-2.5"><Link to="/profile" className="rounded-full border border-blue-400/20 bg-blue-500/10 p-2 text-blue-200"><ChevronRight className="size-4 rotate-180"/></Link><img src={TASKORA_LOGO} alt="TASKORA" className="size-10 rounded-full ring-2 ring-blue-400/40"/><div className="min-w-0 flex-1"><p className="text-lg font-black tracking-[.06em] text-blue-100">Connected Accounts</p><p className="text-[10px] text-slate-400">Connect once. Taskora uses the connected account for verification.</p></div><Link to="/notifications" className="rounded-full border border-blue-400/20 bg-blue-500/10 p-2.5"><Bell className="size-4 text-blue-200"/></Link></header>
 <section className="mb-3.5 rounded-[22px] border border-blue-400/25 bg-[#081a35] p-4"><p className="text-sm font-black">Copy this message</p><p className="mt-1 text-[11px] leading-relaxed text-slate-400">For platforms that use public-bio verification, copy this message and paste it in your public bio.</p><div className="mt-3 rounded-2xl border border-blue-400/20 bg-black/25 p-3 text-[12px] leading-relaxed text-blue-50 whitespace-pre-wrap">{initial.verification.message}</div><button type="button" onClick={()=>{void navigator.clipboard.writeText(initial.verification.message);setCopied(true);setTimeout(()=>setCopied(false),1800);}} className="mt-2 inline-flex items-center gap-2 rounded-xl bg-blue-500 px-3.5 py-2.5 text-xs font-bold text-white"><Copy className="size-3.5"/>{copied?"Copied":"Copy this message"}</button></section>
 <section className="mb-3.5 rounded-[22px] border border-blue-400/15 bg-[#081a35] p-4"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">Platform</p><div className="grid grid-cols-2 gap-2">{CONNECTABLE_PLATFORMS.map(p=><button key={p} type="button" onClick={()=>{setPlatform(p);setValue("");setMsg(null);}} className={\`flex items-center gap-2.5 rounded-2xl border px-3 py-2.5 text-left \${platform===p?"border-blue-400/45 bg-blue-500/15":"border-white/8 bg-black/20"}\`}><PlatformLogo platform={p} size={36}/><span className="text-[12px] font-bold">{platformLabel(p)}</span></button>)}</div></section>
 {platform==="discord"?<section className="mb-3.5 rounded-[22px] border border-blue-400/20 bg-[#081a35] p-4"><p className="text-base font-black">Connect Discord</p><p className="mt-1 text-[11px] text-slate-400">Connect your Discord account. You do not need to enter a Discord username.</p><button type="button" onClick={()=>void discord()} disabled={busy} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-500 py-3.5 text-sm font-black text-white disabled:opacity-50"><Gamepad2 className="size-4"/>{busy?"Opening Discord…":"Connect Discord"}</button></section>:platform==="youtube"?<section className="mb-3.5 rounded-[22px] border border-blue-400/20 bg-[#081a35] p-4"><p className="text-base font-black">Connect YouTube</p><p className="mt-1 text-[11px] text-slate-400">Enter your public YouTube channel URL. Taskora will verify the channel before connecting it.</p><input value={value} onChange={e=>setValue(e.target.value)} placeholder="https://youtube.com/@yourchannel" className="mt-3 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm outline-none focus:border-blue-400/50"/><button type="button" onClick={()=>void verify()} disabled={busy||!value.trim()} className="mt-2.5 w-full rounded-2xl bg-blue-500 py-3.5 text-sm font-black text-white disabled:opacity-50">{busy?"Verifying…":"Verify YouTube Channel"}</button></section>:<section className="mb-3.5 rounded-[22px] border border-blue-400/20 bg-[#081a35] p-4"><p className="text-base font-black">Connect {platformLabel(platform)}</p><p className="mt-1 text-[11px] text-slate-400">Your profile must be public. Copy the message above, paste it in your public bio, then enter your profile URL.</p><input value={value} onChange={e=>setValue(e.target.value)} placeholder="https://your-public-profile-url" className="mt-3 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm outline-none focus:border-blue-400/50"/><button type="button" onClick={()=>void verify()} disabled={busy||!value.trim()} className="mt-2.5 w-full rounded-2xl bg-blue-500 py-3.5 text-sm font-black text-white disabled:opacity-50">{busy?"Verifying…":"Verify Account"}</button></section>}
 {msg?<p className="mb-3 rounded-2xl border border-blue-400/20 bg-blue-500/10 px-3.5 py-3 text-xs text-blue-100">{msg}</p>:null}
 <section><div className="mb-2 flex items-center justify-between"><p className="text-sm font-black">Connected</p><span className="rounded-full border border-blue-400/20 bg-blue-500/10 px-2.5 py-0.5 text-[10px] font-bold text-blue-200">{list.length}</span></div><div className="space-y-2">{list.length===0?<div className="rounded-2xl border border-white/8 bg-[#081a35] p-6 text-center text-sm text-slate-500">No accounts connected yet.</div>:list.map(a=><div key={a.id} className="flex items-center gap-3 rounded-2xl border border-white/8 bg-[#081a35] px-3.5 py-3"><PlatformLogo platform={a.platform as Platform} size={42}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{a.handle||a.external_id}</p><p className="text-[11px] text-slate-400">{platformLabel(a.platform as Platform)}</p></div><span className="inline-flex items-center gap-1 rounded-full border border-blue-400/25 bg-blue-500/10 px-2.5 py-1 text-[10px] font-bold text-blue-100">{a.status==="verified"?<CheckCircle2 className="size-3"/>:null}{a.status==="verified"?"Verified":"Pending"}</span></div>)}</div></section>
 <div className="mt-4 flex items-center gap-2 rounded-2xl border border-blue-400/15 bg-blue-500/5 px-3.5 py-2.5 text-[11px] text-blue-100/80"><Shield className="size-4 shrink-0 text-blue-300"/>Telegram remains your Taskora identity. Other accounts are connected only after verification.</div>
 </main>;
}
