import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Bell, ChevronRight, Shield, CheckCircle2, Copy, Gamepad2, X, ArrowRight, ExternalLink } from "lucide-react";
import { beginDiscordConnect, getConnectedVerificationInfo, listConnectedAccounts, startPublicProfileVerification, verifyPublicProfile, verifyYouTubeChannel } from "@/lib/connected-accounts.functions";
import { CONNECTABLE_PLATFORMS } from "@/lib/taskora-data";
import { PlatformLogo, platformLabel, type Platform } from "@/components/PlatformIcon";
import { TASKORA_LOGO } from "@/lib/brand";

const BIO_LABEL:Record<string,string>={instagram:"Bio",tiktok:"Bio",x:"Bio",facebook:"Bio",linkedin:"About",reddit:"Profile/About",twitch:"Bio",whatsapp:"About"};
const BIO_PLATFORMS=new Set(["x","tiktok","instagram","whatsapp","facebook","reddit","linkedin","twitch"]);

export const Route=createFileRoute("/_authenticated/connected")({
 loader:async()=>{const [accounts,verification]=await Promise.all([listConnectedAccounts().catch(()=>[]),getConnectedVerificationInfo().catch(()=>({referralLink:"",message:""}))]);return{accounts,verification};},
 head:()=>({meta:[{title:"Connected — TASKORA"}]}), component:ConnectedPage
});

function ConnectedPage(){
 const initial=Route.useLoaderData();
 const [platform,setPlatform]=useState<Platform>("youtube");
 const [value,setValue]=useState("");
 const [msg,setMsg]=useState<string|null>(null);
 const [busy,setBusy]=useState(false);
 const [copied,setCopied]=useState(false);
 const [accounts,setAccounts]=useState<any[]>(initial.accounts.filter((a:any)=>a.platform!=="telegram"));
 const [wizard,setWizard]=useState<{token:string;message:string;profileUrl:string;step:number}|null>(null);

 const verify=async()=>{setBusy(true);setMsg(null);try{
   const row=platform==="youtube"?await verifyYouTubeChannel({data:{channelUrl:value}}):await verifyPublicProfile({data:{platform,profileUrl:value,token:wizard?.token||""}});
   setAccounts(p=>[row,...p.filter(a=>a.platform!==platform)]);setValue("");setWizard(null);setMsg("Account verified and connected.");
 }catch(e){setMsg(e instanceof Error?e.message:"Verification failed.");}finally{setBusy(false);}};
 const generate=async()=>{setBusy(true);setMsg(null);try{
   const r=await startPublicProfileVerification({data:{platform,profileUrl:value.trim()}});
   setWizard({token:r.token,message:r.message,profileUrl:r.profileUrl,step:1});
 }catch(e){setMsg(e instanceof Error?e.message:"Could not generate verification message.");}finally{setBusy(false);}};
 const discord=async()=>{setBusy(true);setMsg(null);try{const r=await beginDiscordConnect();window.location.assign(r.url);}catch(e){setMsg(e instanceof Error?e.message:"Discord connection failed.");setBusy(false);}};

 const Wizard=wizard?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 backdrop-blur-sm sm:items-center">
   <div className="w-full max-w-md overflow-hidden rounded-[28px] border border-blue-400/25 bg-[#071a36] shadow-2xl shadow-black/50">
    <div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="text-base font-black">Verify your {platformLabel(platform)} account</p><p className="mt-0.5 text-[10px] text-blue-200/60">Step {wizard.step} of 4</p></div><button type="button" onClick={()=>setWizard(null)} className="rounded-full bg-white/5 p-2"><X className="size-4"/></button></div>
    <div className="p-5">
      <div className="mb-5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-500 transition-all" style={{width:(wizard.step*25)+"%"}}/></div>
      {wizard.step===1?<div><p className="text-xl font-black">1. Copy your message</p><p className="mt-2 text-sm leading-relaxed text-slate-300">Taskora created a unique verification message for this account. Copy the complete message below.</p><div className="mt-4 rounded-2xl border border-blue-400/20 bg-black/25 p-4 text-xs leading-relaxed text-blue-50 whitespace-pre-wrap">{wizard.message}</div><button type="button" onClick={()=>{void navigator.clipboard.writeText(wizard.message);setCopied(true);setTimeout(()=>setCopied(false),1500);}} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-500 py-3.5 text-sm font-black">{copied?<><CheckCircle2 className="size-4"/>Copied</>:<><Copy className="size-4"/>Copy message</>}</button></div>:null}
      {wizard.step===2?<div><p className="text-xl font-black">2. Open your profile</p><p className="mt-2 text-sm leading-relaxed text-slate-300">Open your public {platformLabel(platform)} profile and go to your <b className="text-white">{BIO_LABEL[platform]||"Bio / About"}</b> section.</p><div className="mt-5 rounded-2xl border border-blue-400/15 bg-blue-500/5 p-4"><p className="text-sm font-bold">Use the same profile URL</p><p className="mt-1 break-all text-[11px] text-blue-100/60">{wizard.profileUrl}</p></div></div>:null}
      {wizard.step===3?<div><p className="text-xl font-black">3. Paste it publicly</p><p className="mt-2 text-sm leading-relaxed text-slate-300">Paste the complete message into your public <b className="text-white">{BIO_LABEL[platform]||"Bio"}</b> and save your profile.</p><div className="mt-4 space-y-2 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-4 text-xs text-amber-100"><p>• Do not edit the verification link.</p><p>• Do not put it in a private post or DM.</p><p>• Your profile must be publicly accessible.</p></div></div>:null}
      {wizard.step===4?<div><p className="text-xl font-black">4. Return and verify</p><p className="mt-2 text-sm leading-relaxed text-slate-300">After saving your profile, return here. Taskora will check the public page for your unique verification token.</p><div className="mt-4 rounded-2xl border border-blue-400/20 bg-blue-500/5 p-4"><p className="text-xs font-bold text-blue-100">Security check</p><p className="mt-1 text-[11px] leading-relaxed text-blue-100/60">The token is unique to this Taskora account and verification attempt. A copied message from another account will not verify yours.</p></div></div>:null}
      <div className="mt-5 flex gap-2">{wizard.step>1?<button type="button" onClick={()=>setWizard(w=>w?{...w,step:w.step-1}:w)} className="flex-1 rounded-2xl border border-white/10 bg-white/5 py-3.5 text-sm font-bold">Back</button>:null}{wizard.step<4?<button type="button" onClick={()=>setWizard(w=>w?{...w,step:w.step+1}:w)} className="flex-1 rounded-2xl bg-blue-500 py-3.5 text-sm font-black">Next <ArrowRight className="ml-1 inline size-4"/></button>:<button type="button" disabled={busy} onClick={()=>void verify()} className="flex-1 rounded-2xl bg-blue-500 py-3.5 text-sm font-black disabled:opacity-50">{busy?"Checking…":"Verify my profile"}</button>}</div>
    </div>
   </div>
 </div>:null;

 return <main className="mx-auto min-h-screen w-full max-w-md px-3.5 pb-28 pt-3 text-white">
  {Wizard}
  <header className="mb-4 flex items-center gap-2.5"><Link to="/profile" className="rounded-full border border-blue-400/20 bg-blue-500/10 p-2 text-blue-200"><ChevronRight className="size-4 rotate-180"/></Link><img src={TASKORA_LOGO} alt="TASKORA" className="size-10 rounded-full ring-2 ring-blue-400/40"/><div className="min-w-0 flex-1"><p className="text-lg font-black tracking-[.06em] text-blue-100">Connected Accounts</p><p className="text-[10px] text-slate-400">Connect accounts so Taskora can verify eligible tasks.</p></div><Link to="/notifications" className="rounded-full border border-blue-400/20 bg-blue-500/10 p-2.5"><Bell className="size-4 text-blue-200"/></Link></header>
  <section className="mb-3.5 rounded-[22px] border border-blue-400/20 bg-[#081a35] p-4"><p className="text-sm font-black">Secure account verification</p><p className="mt-1 text-[11px] leading-relaxed text-slate-400">For platforms without a direct integration, Taskora creates a unique message, checks the public profile itself, and only marks the account verified when the token is found.</p></section>
  <section className="mb-3.5 rounded-[22px] border border-blue-400/15 bg-[#081a35] p-4"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">Platform</p><div className="grid grid-cols-2 gap-2">{CONNECTABLE_PLATFORMS.map(p=><button key={p} type="button" onClick={()=>{setPlatform(p);setValue("");setWizard(null);setMsg(null);}} className={"flex items-center gap-2.5 rounded-2xl border px-3 py-2.5 text-left "+(platform===p?"border-blue-400/45 bg-blue-500/15":"border-white/8 bg-black/20")}><PlatformLogo platform={p} size={36}/><span className="text-[12px] font-bold">{platformLabel(p)}</span></button>)}</div></section>
  {platform==="discord"?<section className="mb-3.5 rounded-[22px] border border-blue-400/20 bg-[#081a35] p-4"><p className="text-base font-black">Connect Discord</p><p className="mt-1 text-[11px] text-slate-400">Connect the actual Discord account through OAuth. You do not enter a Discord username.</p><button type="button" onClick={()=>void discord()} disabled={busy} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-500 py-3.5 text-sm font-black"><Gamepad2 className="size-4"/>{busy?"Opening Discord…":"Connect Discord"}</button></section>:platform==="youtube"?<section className="mb-3.5 rounded-[22px] border border-blue-400/20 bg-[#081a35] p-4"><p className="text-base font-black">Connect YouTube</p><p className="mt-1 text-[11px] text-slate-400">Enter your public YouTube channel URL. Taskora verifies the channel through the configured YouTube integration.</p><input value={value} onChange={e=>setValue(e.target.value)} placeholder="https://youtube.com/@yourchannel" className="mt-3 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm outline-none focus:border-blue-400/50"/><button type="button" onClick={()=>void verify()} disabled={busy||!value.trim()} className="mt-2.5 w-full rounded-2xl bg-blue-500 py-3.5 text-sm font-black disabled:opacity-50">{busy?"Verifying…":"Verify YouTube Channel"}</button></section>:<section className="mb-3.5 rounded-[22px] border border-blue-400/20 bg-[#081a35] p-4"><p className="text-base font-black">Connect {platformLabel(platform)}</p><p className="mt-1 text-[11px] leading-relaxed text-slate-400">Enter your public profile URL, then generate a unique message. Taskora will guide you through the 4 steps and verify the public profile itself.</p><input value={value} onChange={e=>setValue(e.target.value)} placeholder="https://your-public-profile-url" className="mt-3 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm outline-none focus:border-blue-400/50"/><button type="button" onClick={()=>void generate()} disabled={busy||!value.trim()} className="mt-2.5 w-full rounded-2xl bg-blue-500 py-3.5 text-sm font-black disabled:opacity-50">{busy?"Generating…":"Generate verification message"}</button></section>}
  {msg?<p className="mb-3 rounded-2xl border border-blue-400/20 bg-blue-500/10 px-3.5 py-3 text-xs text-blue-100">{msg}</p>:null}
  <section><div className="mb-2 flex items-center justify-between"><p className="text-sm font-black">Connected</p><span className="rounded-full border border-blue-400/20 bg-blue-500/10 px-2.5 py-0.5 text-[10px] font-bold text-blue-200">{accounts.length}</span></div><div className="space-y-2">{accounts.length===0?<div className="rounded-2xl border border-white/8 bg-[#081a35] p-6 text-center text-sm text-slate-500">No accounts connected yet.</div>:accounts.map(a=><div key={a.id} className="flex items-center gap-3 rounded-2xl border border-white/8 bg-[#081a35] px-3.5 py-3"><PlatformLogo platform={a.platform as Platform} size={42}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{a.handle||a.external_id}</p><p className="text-[11px] text-slate-400">{platformLabel(a.platform as Platform)}</p></div><span className="inline-flex items-center gap-1 rounded-full border border-blue-400/25 bg-blue-500/10 px-2.5 py-1 text-[10px] font-bold text-blue-100">{a.status==="verified"?<CheckCircle2 className="size-3"/>:null}{a.status==="verified"?"Verified":"Pending"}</span></div>)}</div></section>
  <div className="mt-4 flex items-center gap-2 rounded-2xl border border-blue-400/15 bg-blue-500/5 px-3.5 py-2.5 text-[11px] text-blue-100/80"><Shield className="size-4 shrink-0 text-blue-300"/>Telegram remains your Taskora identity. Other accounts are connected only after verification.</div>
 </main>;
}
