import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, ClipboardCheck, PlayCircle, ChevronRight } from "lucide-react";
import { listDailyMissions, claimRewardedAd, finishRewardedAd } from "@/lib/daily-missions.functions";
import { formatUsd } from "@/lib/taskora-display";
declare global { interface Window { Adsgram?: { init:(o:{blockId:string})=>{show:()=>Promise<unknown>} } } }

export const Route=createFileRoute("/_authenticated/daily-missions")({loader:async()=>({missions:await listDailyMissions().catch(()=>[]) }),component:DailyMissionsPage});

function DailyMissionsPage(){
 const initial=Route.useLoaderData();const [missions,setMissions]=useState(initial.missions);const [busy,setBusy]=useState<string|null>(null);const [msg,setMsg]=useState<string|null>(null);
 useEffect(()=>{if(!document.querySelector('script[src="https://sad.adsgram.ai/js/sad.min.js"]')){const s=document.createElement("script");s.src="https://sad.adsgram.ai/js/sad.min.js";s.async=true;document.head.appendChild(s);}},[]);
 async function watchAd(m:any){setBusy(m.id);setMsg(null);try{const session=await claimRewardedAd({data:{missionId:m.id}});if(!window.Adsgram)throw new Error("Ad service is still loading. Try again.");await window.Adsgram.init({blockId:session.placementId}).show();const r=await finishRewardedAd({data:{claimId:session.claimId}});setMsg("Earned "+(r.rewardUsdt?formatUsd(r.rewardUsdt):"")+(r.rewardPoints?" +"+r.rewardPoints+" TP":""));setMissions(v=>v.map(x=>x.id===m.id?{...x,completed:true}:x));}catch(e){setMsg(e instanceof Error?e.message:"Ad could not be completed.");}finally{setBusy(null);}}
 return <main className="mx-auto min-h-screen w-full max-w-md bg-[#05080f] px-3.5 pb-24 pt-4 text-white"><header className="mb-5 flex items-center gap-3"><Link to="/home" className="rounded-full border border-white/10 p-2"><ArrowLeft className="size-4"/></Link><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-300">TASKORA</p><h1 className="text-xl font-black">Daily Missions</h1></div><CalendarDays className="size-5 text-cyan-300"/></header>{msg?<div className="mb-3 rounded-2xl border border-cyan-400/20 bg-cyan-400/5 px-3 py-2.5 text-[11px] text-cyan-100">{msg}</div>:null}<div className="space-y-2.5">{missions.length===0?<div className="rounded-3xl border border-white/10 bg-white/[.03] p-8 text-center"><CalendarDays className="mx-auto size-9 text-slate-600"/><p className="mt-3 text-sm font-bold">No missions today</p><p className="mt-1 text-[10px] text-slate-500">Come back later for new earning missions.</p></div>:missions.map((m:any)=><article key={m.id} className="rounded-2xl border border-blue-400/15 bg-[#0b1628] p-3.5"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300">{m.mission_type==="rewarded_ad"?<PlayCircle className="size-5"/>:<ClipboardCheck className="size-5"/>}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{m.title}</p><p className="mt-1 text-[10px] text-slate-400">{m.description||(m.mission_type==="rewarded_ad"?"Watch a rewarded ad to earn.":"Complete the mission task and submit proof.")}</p></div><span className="shrink-0 rounded-full bg-cyan-400/10 px-2 py-1 text-[10px] font-black text-cyan-200">{Number(m.reward_usdt)>0?formatUsd(m.reward_usdt):"+"+m.reward_points+" TP"}</span></div><div className="mt-3 flex items-center justify-between border-t border-white/5 pt-3"><span className="text-[10px] text-slate-500">{m.mission_type==="rewarded_ad"?m.daily_limit+" ad"+(m.daily_limit===1?"":"s")+" today":(m.completed?"Completed":"1 task today")}</span>{m.mission_type==="rewarded_ad"?<button disabled={busy===m.id||m.completed||!m.adReady} onClick={()=>void watchAd(m)} className="rounded-xl bg-blue-500 px-3.5 py-2 text-[10px] font-black disabled:opacity-40">{busy===m.id?"Watching…":m.completed?"Completed":!m.adReady?"Ad unavailable":"Watch Ad"}</button>:<Link to="/tasks/$taskId" params={{taskId:String(m.task_id)}} className="inline-flex items-center gap-1 rounded-xl bg-blue-500 px-3.5 py-2 text-[10px] font-black">{m.completed?"Completed":"Open Task"}<ChevronRight className="size-3"/></Link>}</div></article>)}</div></main>;
}
