import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, CheckCircle2, PauseCircle, RefreshCw, WalletCards, XCircle } from "lucide-react";
import { listMyPostedTasks } from "@/lib/taskora.functions";

export const Route = createFileRoute("/_authenticated/my-tasks")({ component: MyPostedTasksPage });
const money = (value: unknown) => "$" + Number(value ?? 0).toFixed(4);
const date = (value: unknown) => value ? new Date(String(value)).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "—";

function MyPostedTasksPage() {
  const [tasks, setTasks] = useState<any[]>([]);
  const [busy, setBusy] = useState(true);
  const [error, setError] = useState<string | null>(null);
  async function refresh() { setBusy(true); try { setTasks(await listMyPostedTasks()); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not load your posted tasks."); } finally { setBusy(false); } }
  useEffect(() => { void refresh(); }, []);
  const stats = useMemo(() => ({ total: tasks.length, active: tasks.filter((t) => String(t.status ?? "") === "active" && Boolean(t.is_active)).length, submissions: tasks.reduce((n, t) => n + Number(t.submissions?.total ?? 0), 0), verified: tasks.reduce((n, t) => n + Number(t.submissions?.verified ?? 0), 0) }), [tasks]);
  return <main className="mx-auto min-h-screen w-full max-w-md bg-[#05070c] px-4 pb-28 pt-5 text-white">
    <header className="mb-5 flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-sky-300">Advertiser</p><h1 className="mt-1 text-xl font-black">My Posted Tasks</h1><p className="mt-1 text-[11px] text-white/40">Every task you have posted, with live delivery status.</p></div><button type="button" onClick={() => void refresh()} disabled={busy} aria-label="Refresh posted tasks" className="rounded-xl border border-white/10 p-2 text-white/60"><RefreshCw className={busy ? "size-4 animate-spin" : "size-4"} /></button></header>
    <div className="grid grid-cols-2 gap-2"><Metric label="Posted" value={stats.total} /><Metric label="Active" value={stats.active} /><Metric label="Submissions" value={stats.submissions} /><Metric label="Verified" value={stats.verified} /></div>
    {error ? <div className="mt-4 rounded-2xl border border-red-400/20 bg-red-500/5 p-4 text-xs text-red-200">{error}</div> : null}
    {busy && !tasks.length ? <div className="mt-5 rounded-2xl border border-white/8 bg-[#12151c] p-6 text-center text-xs text-white/40">Loading your posted tasks…</div> : null}
    {!busy && !tasks.length && !error ? <div className="mt-5 rounded-2xl border border-white/8 bg-[#12151c] p-6 text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-sky-500/10 text-sky-300"><WalletCards className="size-5" /></div><p className="mt-3 text-sm font-semibold">No posted tasks yet</p><p className="mt-1 text-[11px] text-white/40">Create a task from Advertise and it will appear here automatically.</p><Link to="/advertise" className="mt-4 inline-flex items-center gap-1.5 rounded-xl bg-emerald-500 px-4 py-2.5 text-xs font-bold">Create a task <ArrowUpRight className="size-3.5" /></Link></div> : null}
    <div className="mt-4 space-y-3">{tasks.map((task) => { const s = task.submissions ?? { total: 0, pending: 0, verified: 0, rejected: 0 }; const status = String(task.status ?? "active"); const slots = task.slots_total == null ? null : Number(task.slots_total); const left = task.slots_left == null ? null : Number(task.slots_left); const progress = slots && slots > 0 ? Math.min(100, Math.max(0, ((slots - Number(left ?? slots)) / slots) * 100)) : 0; return <article key={String(task.id)} className="rounded-2xl border border-white/8 bg-[#12151c] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-sm font-bold">{String(task.title ?? "Untitled task")}</h2><p className="mt-1 text-[10px] text-white/40">{String(task.platform ?? "Platform")} · {String(task.task_type ?? "Task")} · Posted {date(task.created_at)}</p></div><Status status={status} active={Boolean(task.is_active)} /></div><div className="mt-3 grid grid-cols-2 gap-2"><Stat label="Reward" value={money(task.reward)} /><Stat label="Budget" value={task.budget == null ? "—" : money(task.budget)} /><Stat label="Submissions" value={s.total} /><Stat label="Verified" value={s.verified} /></div>{slots !== null ? <><div className="mt-3 flex items-center justify-between text-[10px] text-white/40"><span>Delivery</span><span>{Math.max(0, slots - Number(left ?? 0))}/{slots} completed</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-sky-400" style={{ width: progress + "%" }} /></div></> : null}<div className="mt-3 flex flex-wrap gap-2 text-[10px] text-white/40"><span className="rounded-full border border-white/8 px-2 py-1">{s.pending} pending</span><span className="rounded-full border border-white/8 px-2 py-1">{s.rejected} rejected</span>{task.target_country_name ? <span className="rounded-full border border-white/8 px-2 py-1">{String(task.target_country_name)}</span> : null}</div></article>; })}</div>
  </main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-white/8 bg-[#12151c] p-3"><p className="text-[9px] uppercase tracking-wide text-white/35">{label}</p><p className="mt-1 text-base font-black">{value.toLocaleString()}</p></div>; }
function Stat({ label, value }: { label: string; value: unknown }) { return <div className="rounded-xl border border-white/6 bg-black/15 p-2.5"><p className="text-[9px] text-white/35">{label}</p><p className="mt-0.5 text-xs font-bold text-white/80">{String(value)}</p></div>; }
function Status({ status, active }: { status: string; active: boolean }) { const label = active && status === "active" ? "Live" : status; const Icon = label === "Live" ? CheckCircle2 : label === "paused" ? PauseCircle : label === "completed" ? CheckCircle2 : XCircle; return <span className="inline-flex shrink-0 items-center gap-1 rounded-full border border-white/10 px-2 py-1 text-[9px] font-bold capitalize text-white/55"><Icon className="size-3" />{label}</span>; }
