import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useMemo,useState } from "react";
import { analytics,createBroadcast,deleteTemplate,listBroadcasts,processBroadcast,publishDraft,retryBroadcast,saveTemplate,sendTest,templates,uploadMedia } from "@/lib/telegram-broadcast-v2.functions";

export const Route=createFileRoute("/_authenticated/owner/announce")({component:OwnerAnnounce});
type Button={text:string;url:string}; type MediaType="none"|"image"|"video"|"document"|"audio"|"voice";
const blank=[{text:"",url:""},{text:"",url:""},{text:"",url:""}];
async function b64(file:File){const a=new Uint8Array(await file.arrayBuffer());let s="";for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s);}

function OwnerAnnounce(){
 const [title,setTitle]=useState(""),[body,setBody]=useState(""),[mediaUrl,setMediaUrl]=useState(""),[mediaType,setMediaType]=useState<MediaType>("none"),[mediaName,setMediaName]=useState("");
 const [btns,setBtns]=useState<Button[]>(blank),[aud,setAud]=useState<"all_active"|"all_telegram">("all_active"),[countries,setCountries]=useState(""),[schedule,setSchedule]=useState(""),[silent,setSilent]=useState(false),[protect,setProtect]=useState(false);
 const [tplName,setTplName]=useState(""),[tpls,setTpls]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[stats,setStats]=useState<Record<string,any>>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function refresh(){try{const [a,b]=await Promise.all([listBroadcasts({data:undefined as never}),templates({data:undefined as never})]);setItems(a);setTpls(b);}catch(e){setMsg(e instanceof Error?e.message:"Load failed");}}
 useEffect(()=>{void refresh()},[]);
 const clean=useMemo(()=>btns.filter(x=>x.text.trim()&&x.url.trim()),[btns]);
 const input=(draft=false)=>({title,body,mediaUrl,mediaType,buttons:clean,audience:aud,countryCodes:countries.split(",").map(x=>x.trim().toUpperCase()).filter(Boolean),scheduledAt:schedule?new Date(schedule).toISOString():undefined,disableNotification:silent,protectContent:protect,saveDraft:draft});
 function reset(){setTitle("");setBody("");setMediaUrl("");setMediaType("none");setMediaName("");setBtns(blank);setCountries("");setSchedule("");}
 async function upload(file?:File){if(!file)return;setBusy(true);setMsg("Uploading…");try{const r=await uploadMedia({data:{name:file.name,type:file.type,data:await b64(file)}});setMediaUrl(r.url);setMediaType(r.mediaType as MediaType);setMediaName(file.name);setMsg("Media uploaded.");}catch(e){setMsg(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
 async function run(fn:()=>Promise<any>,success:string){setBusy(true);setMsg("");try{await fn();await refresh();setMsg(success)}catch(e){setMsg(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 function load(t:any){setTitle(t.title||"");setBody(t.body||"");setMediaUrl(t.media_url||"");setMediaType(t.media_type||"none");setBtns(([...(Array.isArray(t.buttons)?t.buttons:[]),...blank] as Button[]).slice(0,3));setSilent(!!t.disable_notification);setProtect(!!t.protect_content);setMsg(`Loaded “${t.name}”.`)}
 return <main className="mx-auto min-h-screen w-full max-w-6xl bg-[#05070c] px-4 pb-28 pt-5 text-white">
  <header className="mb-5 flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold">Broadcast</h1><p className="mt-1 text-xs text-white/45">Real Telegram campaigns with media uploads, audiences, templates, scheduling and delivery analytics.</p></div><span className="rounded-full border border-sky-400/20 bg-sky-400/10 px-3 py-1 text-[10px] font-bold text-sky-200">LIVE</span></header>
  <div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
   <section className="rounded-2xl border border-white/10 bg-[#12141c] p-4">
    <div className="grid gap-3 sm:grid-cols-2"><div><label className="text-[10px] uppercase tracking-wider text-white/40">Title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Announcement title" className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm"/></div><div><label className="text-[10px] uppercase tracking-wider text-white/40">Schedule</label><input type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)} className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm"/></div></div>
    <label className="mt-4 block text-[10px] uppercase tracking-wider text-white/40">Message</label><textarea value={body} onChange={e=>setBody(e.target.value)} rows={8} placeholder="Telegram HTML formatting is supported." className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm leading-5"/><p className="mt-1 text-[10px] text-white/35">{body.length}/4096</p>
    <div className="mt-4 rounded-xl border border-white/8 bg-black/20 p-3"><div className="flex justify-between"><label className="text-[10px] uppercase tracking-wider text-white/40">Media</label>{mediaUrl&&<button onClick={()=>{setMediaUrl("");setMediaType("none");setMediaName("")}} className="text-[10px] text-rose-300">Remove</button>}</div><div className="mt-2 flex flex-wrap gap-2"><label className="cursor-pointer rounded-xl border border-sky-400/25 bg-sky-400/10 px-3 py-2 text-xs font-semibold text-sky-200"><input className="hidden" type="file" accept="image/*,video/*,audio/*,application/pdf,text/plain" onChange={e=>void upload(e.target.files?.[0])}/>Upload media</label>{mediaName&&<span className="self-center text-[10px] text-white/50">{mediaName} · {mediaType}</span>}</div><input value={mediaUrl} onChange={e=>{setMediaUrl(e.target.value);if(e.target.value&&!mediaType)setMediaType("image")}} placeholder="Or paste a public media URL" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"/></div>
    <div className="mt-4 rounded-xl border border-white/8 bg-black/20 p-3"><label className="text-[10px] uppercase tracking-wider text-white/40">Buttons · up to 3</label>{btns.map((b,i)=><div key={i} className="mt-2 grid grid-cols-2 gap-2"><input value={b.text} onChange={e=>setBtns(x=>x.map((v,n)=>n===i?{...v,text:e.target.value}:v))} placeholder={`Button ${i+1}`} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"/><input value={b.url} onChange={e=>setBtns(x=>x.map((v,n)=>n===i?{...v,url:e.target.value}:v))} placeholder="https://..." className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"/></div>)}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="text-[10px] uppercase tracking-wider text-white/40">Audience</label><select value={aud} onChange={e=>setAud(e.target.value as any)} className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-xs"><option value="all_active">All active Telegram users</option><option value="all_telegram">All Telegram-linked users</option></select></div><div><label className="text-[10px] uppercase tracking-wider text-white/40">Country filter</label><input value={countries} onChange={e=>setCountries(e.target.value)} placeholder="NG, GH, KE" className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-xs"/></div></div>
    <div className="mt-3 grid grid-cols-2 gap-2"><label className="rounded-xl border border-white/8 bg-black/20 px-3 py-2 text-xs"><input type="checkbox" checked={silent} onChange={e=>setSilent(e.target.checked)}/> <span className="ml-1">Silent</span></label><label className="rounded-xl border border-white/8 bg-black/20 px-3 py-2 text-xs"><input type="checkbox" checked={protect} onChange={e=>setProtect(e.target.checked)}/> <span className="ml-1">Protect forwarding</span></label></div>
    <div className="mt-5 grid gap-2 sm:grid-cols-4"><button disabled={busy||!body.trim()} onClick={()=>void run(()=>sendTest({data:input()}),"Test sent.")} className="rounded-2xl border border-sky-400/25 bg-sky-400/10 py-3 text-xs font-bold text-sky-200 disabled:opacity-40">Send Test</button><button disabled={busy||!title.trim()||!body.trim()} onClick={()=>void run(async()=>{await createBroadcast({data:input(true)});reset()},"Draft saved.")} className="rounded-2xl border border-white/10 bg-white/5 py-3 text-xs font-bold disabled:opacity-40">Save Draft</button><button disabled={busy||!tplName.trim()||!title.trim()||!body.trim()} onClick={()=>void run(()=>saveTemplate({data:{...input(),name:tplName}}),"Template saved.")} className="rounded-2xl border border-violet-400/20 bg-violet-400/10 py-3 text-xs font-bold text-violet-200 disabled:opacity-40">Save Template</button><button disabled={busy||!title.trim()||!body.trim()} onClick={()=>void run(async()=>{const b=await createBroadcast({data:input()});if(!b.scheduled_at||Date.parse(b.scheduled_at)<=Date.now())await processBroadcast({data:{id:b.id}});reset()},schedule?"Broadcast scheduled.":"Broadcast queued.")} className="rounded-2xl bg-gradient-to-r from-sky-400 to-blue-500 py-3 text-xs font-bold text-[#071019] disabled:opacity-40">{schedule?"Schedule":"Send"} Broadcast</button></div>
    <input value={tplName} onChange={e=>setTplName(e.target.value)} placeholder="Template name (only needed for Save Template)" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-[11px]"/>{msg&&<p className="mt-3 text-center text-xs text-white/55">{msg}</p>}
   </section>
   <aside className="space-y-4">
    <div className="rounded-2xl border border-white/10 bg-[#12141c] p-4"><p className="text-[10px] uppercase tracking-wider text-white/40">Preview</p><div className="mt-3 overflow-hidden rounded-2xl bg-[#18212b]">{mediaUrl&&mediaType==="image"&&<img src={mediaUrl} alt="" className="max-h-56 w-full object-cover"/>}<div className="p-3"><b>{title||"Announcement title"}</b><p className="mt-2 whitespace-pre-wrap text-sm text-white/80">{body||"Your Telegram message will appear here."}</p>{clean.map((b,i)=><div key={i} className="mt-2 rounded-lg bg-sky-400/15 py-2 text-center text-xs font-bold text-sky-200">{b.text}</div>)}</div></div></div>
    <div className="rounded-2xl border border-white/10 bg-[#12141c] p-4"><div className="flex justify-between"><p className="text-[10px] uppercase tracking-wider text-white/40">Templates</p><button onClick={()=>void refresh()} className="text-[10px] text-sky-300">Refresh</button></div>{tpls.map(t=><div key={t.id} className="mt-2 flex gap-2 rounded-xl border border-white/8 bg-black/20 p-2.5"><button onClick={()=>load(t)} className="min-w-0 flex-1 text-left"><p className="truncate text-xs font-semibold">{t.name}</p><p className="truncate text-[10px] text-white/40">{t.title}</p></button><button onClick={()=>void run(()=>deleteTemplate({data:{id:t.id}}),"Template deleted.")} className="text-[10px] text-rose-300">Delete</button></div>)}{!tpls.length&&<p className="mt-2 text-xs text-white/35">No templates yet.</p>}</div>
   </aside>
  </div>
  <section className="mt-4 rounded-2xl border border-white/10 bg-[#12141c] p-4"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-wider text-white/40">Queue & analytics</p><p className="mt-1 text-xs text-white/35">Delivery state and click tracking persist in Supabase.</p></div><button onClick={()=>void refresh()} className="text-xs text-sky-300">Refresh</button></div>
   <div className="mt-3 space-y-2">{items.map(b=><div key={b.id} className="rounded-xl border border-white/8 bg-black/20 p-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-xs font-bold">{b.title}<em className="ml-2 rounded-full bg-white/5 px-2 py-1 text-[9px] not-italic text-white/45">{b.status}</em></span>{b.scheduled_at&&<span className="text-[9px] text-sky-300">{new Date(b.scheduled_at).toLocaleString()}</span>}</div><div className="mt-2 grid grid-cols-5 gap-1 text-center text-[10px]"><span><b>{b.total_recipients}</b><br/>Audience</span><span className="text-emerald-300"><b>{b.sent_count}</b><br/>Sent</span><span className="text-rose-300"><b>{b.failed_count}</b><br/>Failed</span><span className="text-amber-300"><b>{b.blocked_count}</b><br/>Blocked</span><span className="text-sky-300"><b>{b.click_count||0}</b><br/>Clicks</span></div><div className="mt-2 flex gap-2">{b.status==="draft"&&<button disabled={busy} onClick={()=>void run(async()=>{const u=await publishDraft({data:{id:b.id}});if(!u.scheduled_at||Date.parse(u.scheduled_at)<=Date.now())await processBroadcast({data:{id:b.id}})},"Draft published.")} className="rounded-lg border border-sky-400/20 bg-sky-400/10 px-3 py-1.5 text-[10px] font-semibold text-sky-200">Publish</button>}{b.failed_count>0&&<button disabled={busy} onClick={()=>void run(()=>retryBroadcast({data:{id:b.id}}),"Retry complete.")} className="rounded-lg border border-rose-400/20 bg-rose-400/10 px-3 py-1.5 text-[10px] font-semibold text-rose-200">Retry failed</button>}<button onClick={()=>void analytics({data:{id:b.id}}).then(x=>setStats(s=>({...s,[b.id]:x})))} className="rounded-lg border border-white/10 px-3 py-1.5 text-[10px]">Analytics</button></div>{stats[b.id]&&<div className="mt-2 rounded-lg border border-white/8 p-2 text-[10px] text-white/55">Tracked clicks: <b className="text-white">{stats[b.id].clicks}</b>{stats[b.id].byButton.map((x:any)=><span key={x.buttonIndex} className="ml-2 rounded-full bg-white/5 px-2 py-1">Button {x.buttonIndex+1}: {x.count}</span>)}</div>}</div>)}{!items.length&&<p className="py-8 text-center text-xs text-white/35">No broadcasts yet.</p>}</div>
  </section>
 </main>
}
