import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { OwnerShell } from "@/components/OwnerShell";
import { ownerGetPayoutPolicy, ownerSetPayoutPolicy } from "@/lib/owner-payout-policy.functions";
export const Route=createFileRoute("/_authenticated/owner/payout-policy")({loader:async()=>{try{const policy=await ownerGetPayoutPolicy();return{policy,error:null as string|null};}catch(e){return{policy:null,error:e instanceof Error?e.message:"Owner required"};}},component:PayoutPolicyPage});
function PayoutPolicyPage(){
 const initial=Route.useLoaderData(); const [policy,setPolicy]=useState(initial.policy); const [channel,setChannel]=useState(initial.channel); const [channelId,setChannelId]=useState(initial.channel?.channel_id??""); const [template,setTemplate]=useState(initial.channel?.message_template??DEFAULT_TEMPLATE); const [msg,setMsg]=useState(initial.error); const [busy,setBusy]=useState(false); const [testBusy,setTestBusy]=useState(false); const [channelBusy,setChannelBusy]=useState(false); const [presentationBusy,setPresentationBusy]=useState(false); const [deny,setDeny]=useState((initial.policy?.country_deny??[]).join(",")); const [allow,setAllow]=useState((initial.policy?.country_allow??[]).join(","));
 if(!policy)return <OwnerShell><main className="mx-auto w-full max-w-[1180px] px-4 py-6 text-white"><h1 className="text-xl font-bold">Payout policy</h1><p className="mt-2 text-sm text-amber-200">{msg??"Load failed"}</p></main></OwnerShell>;
 async function savePolicy(){setBusy(true);setMsg(null);try{const r=await ownerSetPayoutPolicy({data:{risk_force_dual:Number(policy.risk_force_dual),risk_auto_freeze:Number(policy.risk_auto_freeze),max_withdrawals_per_day:Number(policy.max_withdrawals_per_day),country_deny:deny.split(/[,\s]+/).map(s=>s.trim()).filter(Boolean),country_allow:allow.split(/[,\s]+/).map(s=>s.trim()).filter(Boolean)}});setPolicy(r.policy);setMsg("Payout policy saved.");}catch(e){setMsg(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false);}}
 async function saveChannel(){setChannelBusy(true);setMsg(null);try{const r=await ownerSetPayoutChannel({data:{channel_id:channelId.trim()}});setChannel(r);setChannelId(r.channel_id??"");setMsg("Payment channel saved. Refresh the preview to load its live profile.");}catch(e){setMsg(e instanceof Error?e.message:"Channel save failed.");}finally{setChannelBusy(false);}}
 async function testPayout(){setTestBusy(true);setMsg(null);try{const r=await ownerTestPayoutProof();setMsg(`Test payout sent successfully. Telegram message #${r.message_id ?? "sent"}`);}catch(e){setMsg(e instanceof Error?e.message:"Test payout failed.");}finally{setTestBusy(false);}}
 async function refreshChannel(){setChannelBusy(true);setMsg(null);try{const r=await ownerRefreshPayoutChannel();setChannel(r);setChannelId(r.channel_id??"");setTemplate(r.message_template??DEFAULT_TEMPLATE);setMsg("Channel profile refreshed from Telegram.");}catch(e){setMsg(e instanceof Error?e.message:"Channel preview failed.");}finally{setChannelBusy(false);}}
 async function savePresentation(){setPresentationBusy(true);setMsg(null);try{const input=document.getElementById("payout-proof-image") as HTMLInputElement|null;const file=input?.files?.[0];let dataUrl:string|undefined;if(file){if(!file.type.startsWith("image/"))throw new Error("Choose an image file.");if(file.size>3*1024*1024)throw new Error("Keep the payout image under 3 MB.");dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Could not read image."));reader.readAsDataURL(file);});}const presentationData: { message_template: string; payout_image_data_url?: string; payout_image_file_name?: string } = { message_template: template };
if (dataUrl) presentationData.payout_image_data_url = dataUrl;
if (file?.name) presentationData.payout_image_file_name = file.name;
const r=await ownerSetPayoutPresentation({data:presentationData});setChannel(r);setTemplate(r.message_template??DEFAULT_TEMPLATE);if(input)input.value="";setMsg("Payout message and image saved.");}catch(e){setMsg(e instanceof Error?e.message:"Presentation save failed.");}finally{setPresentationBusy(false);}}
 return <OwnerShell><main className="mx-auto w-full max-w-[1180px] px-4 pb-10 pt-5 text-white"><h1 className="text-xl font-bold">Payout policy</h1><p className="mt-1 text-xs text-white/45">Risk rules and withdrawal limits.</p>{msg?<p className="mt-3 rounded-xl border border-cyan-400/15 bg-cyan-400/5 px-3 py-2 text-xs text-cyan-200">{msg}</p>:null}

 <section className="mt-5 space-y-3"><label className="block text-[11px] text-white/50">Force dual-approval at risk ≥<input type="number" min={0} max={100} value={policy.risk_force_dual} onChange={e=>setPolicy({...policy,risk_force_dual:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0b1d36] px-3 py-2 text-sm"/></label><label className="block text-[11px] text-white/50">Auto-freeze at risk ≥ (0 = off)<input type="number" min={0} max={100} value={policy.risk_auto_freeze} onChange={e=>setPolicy({...policy,risk_auto_freeze:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0b1d36] px-3 py-2 text-sm"/></label><label className="block text-[11px] text-white/50">Max WD requests / 24h<input type="number" min={1} max={20} value={policy.max_withdrawals_per_day} onChange={e=>setPolicy({...policy,max_withdrawals_per_day:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0b1d36] px-3 py-2 text-sm"/></label><label className="block text-[11px] text-white/50">Country deny (ISO, comma-separated)<input value={deny} onChange={e=>setDeny(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0b1d36] px-3 py-2 text-sm"/></label><label className="block text-[11px] text-white/50">Country allow only (empty = all)<input value={allow} onChange={e=>setAllow(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0b1d36] px-3 py-2 text-sm"/></label><button type="button" disabled={busy} onClick={()=>void savePolicy()} className="w-full rounded-xl bg-gradient-to-r from-blue-500 to-sky-500 py-3 text-sm font-bold disabled:opacity-50">{busy?"Saving…":"Save policy"}</button></section>
 </main></OwnerShell>;
}
