import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useMemo,useState } from "react";
import { createTelegramBroadcast,deleteTelegramBroadcastTemplate,getTelegramBroadcastAnalytics,listTelegramBroadcastTemplates,listTelegramBroadcasts,processTelegramBroadcast,publishTelegramBroadcast,retryFailedTelegramBroadcast,saveTelegramBroadcastTemplate,sendTelegramBroadcastTest,uploadTelegramBroadcastMedia } from "@/lib/telegram-broadcast.functions";

export const Route=createFileRoute("/_authenticated/owner/announce")({component:OwnerAnnounce});
type MediaType="none"|"image"|"video"|"document"|"audio"|"voice";
type Button={text:string;url:string};
const blank:Button[]=[{text:"",url:""},{text:"",url:""},{text:"",url:""}];

async function base64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let out="";for(let i=0;i<bytes.length;i+=32768)out+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(out);}

function OwnerAnnounce(){
 const [title,setTitle]=useState(""),[body,setBody]=useState(""),[mediaUrl,setMediaUrl]=useState(""),[mediaType,setMediaType]=useState<MediaType>("none"),[mediaName,setMediaName]=useState("");
 const [buttons,setButtons]=useState<Button[]>(blank),[audience,setAudience]=useState<"all_active"|"all_telegram">("all_active"),[countries,setCountries]=useState(""),[scheduledAt,setScheduledAt]=useState("");
 const [silent,setSilent]=useState(false),[protect,setProtect]=useState(false),[templateName,setTemplateName]=useState(""),[templates,setTemplates]=useState<any[]>([]),[stats,setStats]=useState<Record<string,any>>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[items,setItems]=useState<any[]>([]);
 async function refresh(){try{const [a,b]=await Promise.all([listTelegramBroadcasts({data:undefined as never}),listTelegramBroadcastTemplates({data:undefined as never})]);setItems(a);setTemplates(b)}catch(e){setMsg(e instanceof Error?e.message:"Failed to load broadcasts")}}
 useEffect(()=>{void refresh()},[]);
 const clean=useMemo(()=>buttons.filter(b=>b.text.trim()&&b.url.trim()),[buttons]);
 const input=(draft=false)=>({title,body,mediaUrl,mediaType,buttons:clean,audience,countryCodes:countries.split(",").map(x=>x.trim().toUpperCase()).filter(Boolean),scheduledAt:scheduledAt?new Date(scheduledAt).toISOString():undefined,disableNotification:silent,protectContent:protect,saveDraft:draft});
 function reset(){setTitle("");setBody("");setMediaUrl("");setMediaType("none");setMediaName("");setButtons(blank);setCountries("");setScheduledAt("");setSilent(false);setProtect(false)}
 async function run(fn:()=>Promise<any>,success:string){setBusy(true);setMsg("");try{await fn();await refresh();setMsg(success)}catch(e){setMsg(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 async function saveTemplate(){if(!templateName.trim())return setMsg("Enter a template name.");setBusy(true);try{await saveTelegramBroadcastTemplate({data:{...input(),name:templateName.trim()}});setTemplateName("");await refresh();setMsg("Template saved.")}catch(e){setMsg(e instanceof Error?e.message:"Template save failed")}finally{setBusy(false)}}
 function loadTemplate(t:any){setTitle(t.title||"");setBody(t.body||"");setMediaUrl(t.media_url||"");setMediaType(t.media_type||"none");setButtons(([...(Array.isArray(t.buttons)?t.buttons:[]),...blank] as Button[]).slice(0,3));setSilent(!!t.disable_notification);setProtect(!!t.protect_content);setMsg(`Loaded “${t.name}”.`)}
 async function showAnalytics(id:string){try{const result=await getTelegramBroadcastAnalytics({data:{broadcastId:id}});setStats(s=>({...s,[id]:result}))}catch(e){setMsg(e instanceof Error?e.message:"Analytics failed")}}
 async function upload(file?:File){if(!file)return;setBusy(true);setMsg("Uploading media…");try{const r=await uploadTelegramBroadcastMedia({data:{name:file.name,type:file.type,data:await base64(file)}});setMediaUrl(r.url);setMediaType(r.mediaType as MediaType);setMediaName(file.name);setMsg("Media uploaded and ready.")}catch(e){setMsg(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
 return <main className="mx-auto min-h-screen w-full max-w-6xl bg-[#05070c] px-4 pb-28 pt-5 text-white">
  <header className="mb-5 flex items-start justify-between"><div><h1 className="text-xl font-bold">Broadcast</h1><p className="mt-1 text-xs text-white/45">Real Telegram campaigns with media, targeting, scheduling, drafts and persistent delivery.</p></div><span className="rounded-full border border-sky-400/20 bg-sky-400/10 px-3 py-1 text-[10px] font-bold text-sky-200">LIVE BOT</span></header>
  <div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
   <section className="rounded-2xl border border-white/10 bg-[#12141c] p-4">
    <div className="grid gap-3 sm:grid-cols-2"><div><label className="text-[10px] uppercase tracking-wider text-white/40">Title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Announcement title" className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm"/></div><div><label className="text-[10px] uppercase tracking-wider text-white/40">Schedule</label><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm"/></div></div>
    <label className="mt-4 block text-[10px] uppercase tracking-wider text-white/40">Message</label><textarea value={body} onChange={e=>setBody(e.target.value)} rows={8} placeholder="Telegram HTML formatting is supported." className="mt-1.5 w-full resize-y rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm leading-5"/><p className="mt-1 text-[10px] text-white/35">{body.length}/4096</p>
    <div className="mt-4 rounded-xl border border-white/8 bg-black/20 p-3"><div className="flex items-center justify-between"><label className="text-[10px] uppercase tracking-wider text-white/40">Media</label>{mediaUrl&&<button onClick={()=>{setMediaUrl("");setMediaType("none");setMediaName("")}} className="text-[10px] text-rose-300">Remove</button>}</div><div className="mt-2 flex flex-wrap items-center gap-2"><label className="cursor-pointer rounded-xl border border-sky-400/25 bg-sky-400/10 px-3 py-2 text-xs font-semibold text-sky-200"><input className="hidden" type="file" accept="image/*,video/*,audio/*,application/pdf,text/plain" onChange={e=>void upload(e.target.files?.[0])}/>Upload media</label>{mediaName&&<span className="text-[10px] text-white/50">{mediaName} · {mediaType}</span>}</div><input value={mediaUrl} onChange={e=>{setMediaUrl(e.target.value);if(e.target.value&&!mediaType)setMediaType("image")}} placeholder="Or paste a public media URL" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"/></div>
    <div className="mt-4 rounded-xl border border-white/8 bg-black/20 p-3"><label className="text-[10px] uppercase tracking-wider text-white/40">Buttons · up to 3</label>{buttons.map((b,i)=><div key={i} className="mt-2 grid grid-cols-2 gap-2"><input value={b.text} onChange={e=>setButtons(x=>x.map((v,n)=>n===i?{...v,text:e.target.value}:v))} placeholder={`Button ${i+1} text`} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"/><input value={b.url} onChange={e=>setButtons(x=>x.map((v,n)=>n===i?{...v,url:e.target.value}:v))} placeholder="https://..." className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"/></div>)}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="text-[10px] uppercase tracking-wider text-white/40">Audience</label><select value={audience} onChange={e=>setAudience(e.target.value as any)} className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-xs"><option value="all_active">All active Telegram users</option><option value="all_telegram">All Telegram-linked users</option></select></div><div><label className="text-[10px] uppercase tracking-wider text-white/40">Country filter</label><input value={countries} onChange={e=>setCountries(e.target.value)} placeholder="NG, GH, KE" className="mt-1.5 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-xs"/></div></div>
    <div className="mt-3 grid grid-cols-2 gap-2"><label className="rounded-xl border border-white/8 bg-black/20 px-3 py-2 text-xs"><input type="checkbox" checked={silent} onChange={e=>setSilent(e.target.checked)}/> <span className="ml-1">Send silently</span></label><label className="rounded-xl border border-white/8 bg-black/20 px-3 py-2 text-xs"><input type="checkbox" checked={protect} onChange={e=>setProtect(e.target.checked)}/> <span className="ml-1">Protect forwarding</span></label></div>
    <div className="mt-5 grid gap-2 sm:grid-cols-4"><button disabled={busy||!body.trim()} onClick={()=>void run(()=>sendTelegramBroadcastTest({data:input()}),"Test message sent.")} className="rounded-2xl border border-sky-400/25 bg-sky-400/10 py-3 text-xs font-bold text-sky-200 disabled:opacity-40">Send Test</button><button disabled={busy||!title.trim()||!body.trim()} onClick={()=>void run(async()=>{await createTelegramBroadcast({data:input(true)});reset()},"Draft saved.")} className="rounded-2xl border border-white/10 bg-white/5 py-3 text-xs font-bold disabled:opacity-40">Save Draft</button><button disabled={busy||!templateName.trim()||!title.trim()||!body.trim()} onClick={()=>void saveTemplate()} className="rounded-2xl border border-violet-400/20 bg-violet-400/10 py-3 text-xs font-bold text-violet-200">Save Template</button><button disabled={busy||!title.trim()||!body.trim()} onClick={()=>void run(async()=>{const b=await createTelegramBroadcast({data:input()});if(!b.scheduled_at||Date.parse(b.scheduled_at)<=Date.now())await processTelegramBroadcast({data:{broadcastId:b.id}});reset()},scheduledAt?"Broadcast scheduled.":"Broadcast queued.")} className="rounded-2xl bg-gradient-to-r from-sky-400 to-blue-500 py-3 text-xs font-bold text-[#071019] disabled:opacity-40">{scheduledAt?"Schedule":"Send"} Broadcast</button></div>
    <input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="Template name (only needed for Save Template)" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-[11px]"/>{msg&&<p className="mt-3 text-center text-xs text-white/55">{msg}</p>}
   </section>
   <aside className="space-y-4"><div className="rounded-2xl border border-white/10 bg-[#12141c] p-4"><p className="text-[10px] uppercase tracking-wider text-white/40">Telegram preview</p><div className="mt-3 overflow-hidden rounded-2xl bg-[#18212b]">{mediaUrl&&mediaType==="image"&&<img src={mediaUrl} alt="" className="max-h-56 w-full object-cover"/>}<div className="p-3"><b>{title||"Announcement title"}</b><p className="mt-2 whitespace-pre-wrap text-sm text-white/80">{body||"Your Telegram message will appear here."}</p>{clean.map((b,i)=><div key={i} className="mt-2 rounded-lg bg-sky-400/15 py-2 text-center text-xs font-bold text-sky-200">{b.text}</div>)}</div></div><div className="mt-5 rounded-xl border border-white/8 bg-black/20 p-3 text-xs text-white/45">Media is stored in Supabase Storage. Scheduled messages remain queued in Supabase until processed.</div></div><div className="rounded-2xl border border-white/10 bg-[#12141c] p-4"><div className="flex items-center justify-between"><p className="text-[10px] uppercase tracking-wider text-white/40">Templates</p><button onClick={()=>void refresh()} className="text-[10px] text-sky-300">Refresh</button></div>{templates.map(t=><div key={t.id} className="mt-2 flex gap-2 rounded-xl border border-white/8 bg-black/20 p-2.5"><button onClick={()=>loadTemplate(t)} className="min-w-0 flex-1 text-left"><p className="truncate text-xs font-semibold">{t.name}</p><p className="truncate text-[10px] text-white/40">{t.title}</p></button><button onClick={()=>void run(()=>deleteTelegramBroadcastTemplate({data:{id:t.id}}),"Template deleted.")} className="text-[10px] text-rose-300">Delete</button></div>)}{!templates.length&&<p className="mt-2 text-xs text-white/35">No templates yet.</p>}</div></aside>
  </div>
  <section className="mt-4 rounded-2xl border border-white/10 bg-[#12141c] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-white/40">Broadcast queue</p><p className="mt-1 text-xs text-white/35">Delivery records persist across reloads and partial failures.</p></div><button onClick={()=>void refresh()} className="text-xs text-sky-300">Refresh</button></div><div className="mt-3 space-y-2">{items.map(b=><div key={b.id} className="rounded-xl border border-white/8 bg-black/20 p-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-xs font-bold">{b.title}<em className="ml-2 rounded-full bg-white/5 px-2 py-1 text-[9px] not-italic text-white/45">{b.status}</em></span>{b.scheduled_at&&<span className="text-[9px] text-sky-300">{new Date(b.scheduled_at).toLocaleString()}</span>}</div><div className="mt-2 grid grid-cols-4 gap-1 text-center text-[10px]"><span><b>{b.total_recipients}</b><br/>Audience</span><span className="text-emerald-300"><b>{b.sent_count}</b><br/>Sent</span><span className="text-rose-300"><b>{b.failed_count}</b><br/>Failed</span><span className="text-amber-300"><b>{b.blocked_count}</b><br/>Blocked</span></div><div className="mt-2 flex gap-2">{b.status==="draft"&&<button disabled={busy} onClick={()=>void run(async()=>{const u=await publishTelegramBroadcast({data:{broadcastId:b.id}});if(!u.scheduled_at||Date.parse(u.scheduled_at)<=Date.now())await processTelegramBroadcast({data:{broadcastId:b.id}})},"Draft published.")} className="rounded-lg border border-sky-400/20 bg-sky-400/10 px-3 py-1.5 text-[10px] font-semibold text-sky-200">Publish</button>}{b.failed_count>0&&<button disabled={busy} onClick={()=>void run(()=>retryFailedTelegramBroadcast({data:{broadcastId:b.id}}),"Retry complete.")} className="rounded-lg border border-rose-400/20 bg-rose-400/10 px-3 py-1.5 text-[10px] font-semibold text-rose-200">Retry failed</button>}<button onClick={()=>void showAnalytics(b.id)} className="rounded-lg border border-white/10 px-3 py-1.5 text-[10px]">Analytics</button>{stats[b.id]&&<div className="mt-2 rounded-lg border border-white/8 p-2 text-[10px] text-white/55">Tracked clicks: <b className="text-white">{stats[b.id].clicks}</b>{stats[b.id].byButton.map((x:any)=><span key={x.buttonIndex} className="ml-2 rounded-full bg-white/5 px-2 py-1">Button {x.buttonIndex+1}: {x.count}</span>)}</div>}</div></div>)}{!items.length&&<p className="py-8 text-center text-xs text-white/35">No broadcasts yet.</p>}</div></section>
 </main>
}
