import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ShieldCheck, Search, RefreshCw, AlertTriangle, ScanSearch, UserRound, ExternalLink, Clock3 } from "lucide-react";
import { OwnerShell } from "@/components/OwnerShell";
import { getOwnerVerificationDashboard, getOwnerVerificationCaseDetail, reviewVerificationCase, scanVerificationCase } from "@/lib/verification.functions";

export const Route=createFileRoute("/_authenticated/owner/verification")({component:OwnerVerification});

function OwnerVerification(){
 const q=useQuery({queryKey:["owner-verification"],queryFn:()=>getOwnerVerificationDashboard()});
 const [search,setSearch]=useState(""); const [selected,setSelected]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null);
 const detail=useQuery({queryKey:["owner-verification-case",selected],queryFn:()=>getOwnerVerificationCaseDetail({data:{caseId:selected!}}),enabled:Boolean(selected)});
 const review=useMutation({mutationFn:(x:{caseId:string;decision:"verified"|"rejected"|"review";reason?:string})=>reviewVerificationCase({data:x}),onSettled:()=>{q.refetch();detail.refetch()}});
 const scan=useMutation({mutationFn:(caseId:string)=>scanVerificationCase({data:{caseId}}),onSettled:()=>{q.refetch();detail.refetch()}});
 const cases=(q.data?.cases??[]).filter((c:any)=>!search||[c.subject_id,c.subject_type,c.verification_type,c.status,c.reason].join(" ").toLowerCase().includes(search.toLowerCase()));
 if(q.isLoading)return <OwnerShell><div className="p-5 text-slate-300">Loading Verification & Trust…</div></OwnerShell>;
 if(q.error)return <OwnerShell><div className="p-5 text-red-300">{String(q.error)}</div></OwnerShell>;
 const c=q.data?.counts; const d:any=detail.data; const p=d?.snapshot?.profile;
 return <OwnerShell><main className="p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="size-6 text-blue-400"/><h1 className="text-2xl font-semibold">Verification & Trust</h1></div><p className="mt-1 text-sm text-slate-400">Inspect the real user, activity, evidence and automated risk signals before deciding.</p></div><button onClick={()=>q.refetch()} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm"><RefreshCw className="mr-2 inline size-4"/>Refresh</button></div>
  <div className="grid gap-3 grid-cols-2 md:grid-cols-4 xl:grid-cols-8">{Object.entries(c??{}).map(([k,v])=><div key={k} className="rounded-2xl border border-white/10 bg-white/[.03] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">{k}</p><p className="mt-1 text-xl font-semibold">{String(v)}</p></div>)}</div>
  <div className="rounded-2xl border border-white/10 bg-white/[.03] p-3"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search user ID, type, status or reason…" className="w-full rounded-xl border border-white/10 bg-black/10 py-2.5 pl-9 pr-3 text-sm outline-none"/></div></div>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(360px,520px)]">
   <div className="space-y-3">{cases.map((x:any)=><article key={x.id} className={"rounded-2xl border p-4 "+(selected===x.id?"border-blue-400/50 bg-blue-500/[.06]":"border-white/10 bg-white/[.03]")}><button className="w-full text-left" onClick={()=>setSelected(x.id)}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{pretty(x.subject_type)} · {pretty(x.verification_type)}</p><p className="mt-1 break-all text-xs text-slate-500">{x.subject_id} · risk {x.risk_score}</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-xs capitalize">{x.status}</span></div>{x.reason&&<p className="mt-2 flex gap-2 text-sm text-amber-200"><AlertTriangle className="mt-0.5 size-4 shrink-0"/>{x.reason}</p>}</button><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy===x.id} onClick={async()=>{setBusy(x.id);await review.mutateAsync({caseId:x.id,decision:"verified"}).finally(()=>setBusy(null))}} className="rounded-lg bg-emerald-500/15 px-3 py-2 text-xs text-emerald-300 disabled:opacity-50">Verify</button><button disabled={busy===x.id} onClick={async()=>{const reason=window.prompt("Reason for rejection/restriction?")||"Rejected after owner review.";setBusy(x.id);await review.mutateAsync({caseId:x.id,decision:"rejected",reason}).finally(()=>setBusy(null))}} className="rounded-lg bg-red-500/10 px-3 py-2 text-xs text-red-300 disabled:opacity-50">Reject / Restrict</button><button disabled={busy===x.id} onClick={async()=>{setBusy(x.id);await review.mutateAsync({caseId:x.id,decision:"review",reason:"Needs further evidence."}).finally(()=>setBusy(null))}} className="rounded-lg bg-amber-500/10 px-3 py-2 text-xs text-amber-300 disabled:opacity-50">Keep in Review</button><button onClick={()=>setSelected(x.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-200"><UserRound className="mr-1 inline size-3"/>View user</button></div></article>)}{!cases.length&&<div className="rounded-2xl border border-white/10 p-8 text-center text-sm text-slate-500">No verification cases match.</div>}</div>
   <aside className="rounded-2xl border border-white/10 bg-[#07101f] p-4 xl:sticky xl:top-4 xl:h-fit">{!selected?<div className="py-16 text-center text-sm text-slate-500">Select a verification case to inspect the user.</div>:detail.isLoading?<div className="py-16 text-center text-sm text-slate-400">Loading user profile and activity…</div>:detail.error?<div className="py-16 text-center text-sm text-red-300">{String(detail.error)}</div>:<div className="space-y-4">
    <div className="flex items-center gap-3">{p?.photo_url?<img src={p.photo_url} alt="" className="size-16 rounded-full object-cover ring-2 ring-blue-400/40"/>:<div className="flex size-16 items-center justify-center rounded-full bg-blue-500/15 text-xl font-bold">{String(p?.display_name||"U").slice(0,1)}</div>}<div className="min-w-0"><p className="truncate text-lg font-semibold">{p?.display_name||"Unknown user"}</p><p className="text-xs text-slate-400">{p?.username?"@"+p.username:"No username"} · Telegram {p?.telegram_id||"—"}</p><p className="mt-1 text-xs text-slate-500">Joined {p?.created_at?new Date(p.created_at).toLocaleDateString():"—"} · Last active {p?.last_active_at?new Date(p.last_active_at).toLocaleString():"—"}</p></div></div>
    <div className="grid grid-cols-3 gap-2">{[["Status",p?.verification_status],["Trust",p?.verification_level],["Risk",String(p?.risk_score??0)]].map(([k,v])=><div key={String(k)} className="rounded-xl border border-white/10 bg-white/[.03] p-2"><p className="text-[9px] uppercase text-slate-500">{String(k)}</p><p className="mt-1 text-xs font-semibold capitalize">{String(v??"—")}</p></div>)}</div>
    <div className="grid grid-cols-2 gap-2 text-xs"><Mini label="Connected" value={String(d.snapshot.connectedAccounts.length)}/><Mini label="Verified links" value={String(d.snapshot.connectedAccounts.filter((x:any)=>x.status==="verified").length)}/><Mini label="Submissions" value={String(d.snapshot.submissions.length)}/><Mini label="Fraud flags" value={String(d.snapshot.submissions.filter((x:any)=>x.fraud_flag).length)}/><Mini label="Withdrawals" value={String(d.snapshot.withdrawals.length)}/><Mini label="Deposits" value={String(d.snapshot.deposits.length)}/><Mini label="Ad claims" value={String(d.snapshot.claims.length)}/><Mini label="Transactions" value={String(d.snapshot.transactions.length)}/></div>
    <section><h3 className="mb-2 text-sm font-semibold">Connected accounts</h3><div className="space-y-1.5">{d.snapshot.connectedAccounts.slice(0,8).map((a:any)=><div key={a.id} className="rounded-xl border border-white/8 px-3 py-2 text-xs"><div className="flex justify-between gap-2"><span>{pretty(a.platform)} · {a.handle||"—"}</span><span className="capitalize text-slate-400">{a.status}</span></div>{a.profile_url&&<a href={a.profile_url} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-blue-300">View public profile <ExternalLink className="size-3"/></a>}</div>)}{!d.snapshot.connectedAccounts.length&&<p className="text-xs text-slate-500">None.</p>}</div></section>
    <section><h3 className="mb-2 text-sm font-semibold">Recent activity</h3><div className="space-y-1.5 max-h-64 overflow-auto">{[...d.snapshot.submissions.slice(0,8).map((x:any)=>({k:"Task",s:x.status,t:x.created_at,d:x.fraud_flag?"Fraud flag":x.proof_url||x.proof_text||"No proof"})),...d.snapshot.withdrawals.slice(0,5).map((x:any)=>({k:"Withdrawal",s:x.status,t:x.created_at,d:String(x.amount)+" · "+x.method})),...d.snapshot.deposits.slice(0,5).map((x:any)=>({k:"Deposit",s:x.status,t:x.created_at,d:String(x.amount)+" · "+x.method})),...d.snapshot.claims.slice(0,8).map((x:any)=>({k:"Ad reward",s:x.status,t:x.created_at,d:String(x.reward_usdt||0)+" USDT"}))].sort((a,b)=>new Date(b.t).getTime()-new Date(a.t).getTime()).slice(0,18).map((x,i)=><div key={i} className="rounded-xl border border-white/8 px-3 py-2 text-xs"><div className="flex justify-between gap-2"><span>{x.k}</span><span className="capitalize text-slate-400">{x.s}</span></div><p className="mt-0.5 truncate text-slate-500">{x.d}</p></div>)}</div></section>
    <button disabled={scan.isPending} onClick={()=>scan.mutate(selected)} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-500 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><ScanSearch className="size-4"/>{scan.isPending?"Scanning account…":"Scan & Check Account"}</button>
    {scan.data?.result?<div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Latest scan: <span className="capitalize">{scan.data.result.outcome.replace("_"," ")}</span></span><span className="text-sm">Risk {scan.data.result.score}</span></div><div className="mt-2 space-y-1">{scan.data.result.signals.map((s:any)=><p key={s.code} className="text-xs text-slate-300">• {s.message}</p>)}</div></div>:null}
    {d.scanHistory?.length?<section><h3 className="mb-2 flex items-center gap-2 text-sm font-semibold"><Clock3 className="size-4"/>Previous scans</h3><div className="space-y-1.5">{d.scanHistory.map((s:any)=><div key={s.id} className="flex justify-between rounded-xl border border-white/8 px-3 py-2 text-xs"><span className="capitalize">{s.outcome.replace("_"," ")}</span><span>risk {s.risk_score} · {new Date(s.created_at).toLocaleString()}</span></div>)}</div></section>:null}
   </div>}</aside>
  </div>
 </div></main></OwnerShell>;
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/[.03] p-2"><p className="text-[9px] uppercase text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
function pretty(v:any){return String(v??"").replaceAll("_"," ").replace(/\\b\\w/g,m=>m.toUpperCase())}