import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronLeft, CircleHelp, Eye, EyeOff, Gamepad2, Megaphone, PlayCircle, Save, ShieldCheck, WalletCards } from "lucide-react";
import { OwnerShell } from "@/components/OwnerShell";
import { listMonetizationProviders, saveMonetizationProvider, type MonetizationProvider } from "@/lib/monetization.functions";

export const Route=createFileRoute("/_authenticated/owner/monetization")({component:OwnerMonetizationPage});
const GROUPS=[
 {key:"games",label:"Game Providers",icon:Gamepad2,providers:["playgama","gamezop","gamedistribution","gamemonetize","gamepix"]},
 {key:"ads",label:"Rewarded Ads",icon:Megaphone,providers:["admob","applovin_max","unity_levelplay","unity_ads"]},
 {key:"videos",label:"Video Platforms",icon:PlayCircle,providers:["youtube","tiktok","x","instagram","facebook"]},
 {key:"offerwalls",label:"Offerwalls / CPA",icon:WalletCards,providers:["adgem","offerwall_gg","adswedmedia","kooads"]},
] as const;

function OwnerMonetizationPage(){
 const [providers,setProviders]=useState<MonetizationProvider[]>([]); const [selected,setSelected]=useState<string>("playgama"); const [secretValues,setSecretValues]=useState<Record<string,string>>({}); const [showSecret,setShowSecret]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const load=async()=>{try{const rows=await listMonetizationProviders();setProviders(rows);if(!rows.some(p=>p.providerKey===selected)&&rows[0])setSelected(rows[0].providerKey);}catch(e){setMessage(e instanceof Error?e.message:"Could not load monetization providers.");}};
 useEffect(()=>{void load();},[]);
 const provider=providers.find(p=>p.providerKey===selected)??null;
 const group=GROUPS.find(g=>g.providers.includes(selected as any));
 const [form,setForm]=useState({enabled:false,priority:100,apiBaseUrl:"",publicId:"",placementId:"",postbackUrl:"",webhookUrl:"",revenueSharePercent:"",userRewardSharePercent:"",minimumPayoutUsd:""});
 useEffect(()=>{if(provider)setForm({enabled:provider.enabled,priority:provider.priority,apiBaseUrl:provider.apiBaseUrl??"",publicId:provider.publicId??"",placementId:provider.placementId??"",postbackUrl:provider.postbackUrl??"",webhookUrl:provider.webhookUrl??"",revenueSharePercent:provider.revenueSharePercent==null?"":String(provider.revenueSharePercent),userRewardSharePercent:provider.userRewardSharePercent==null?"":String(provider.userRewardSharePercent),minimumPayoutUsd:provider.minimumPayoutUsd==null?"":String(provider.minimumPayoutUsd)});setSecretValues({});setShowSecret(false);},[provider?.id]);
 const secretFields=useMemo(()=>group?.key==="games"?["API Key","API Secret"]:group?.key==="ads"?["App ID / Publisher ID","API Key / Secret"]:group?.key==="videos"?["API Key","API Secret / Access Token"]:["API Key","API Secret / Postback Key"],[group?.key]);
 async function save(){if(!provider)return;setBusy(true);setMessage(null);try{await saveMonetizationProvider({data:{id:provider.id,enabled:form.enabled,priority:Number(form.priority)||100,apiBaseUrl:form.apiBaseUrl,publicId:form.publicId,placementId:form.placementId,postbackUrl:form.postbackUrl,webhookUrl:form.webhookUrl,revenueSharePercent:form.revenueSharePercent===""?null:Number(form.revenueSharePercent),userRewardSharePercent:form.userRewardSharePercent===""?null:Number(form.userRewardSharePercent),minimumPayoutUsd:form.minimumPayoutUsd===""?null:Number(form.minimumPayoutUsd),secrets:Object.entries(secretValues).filter(([,v])=>v.trim()).map(([name,value])=>({name,value}))}});setMessage("Provider settings saved securely.");setSecretValues({});await load();}catch(e){setMessage(e instanceof Error?e.message:"Could not save provider settings.");}finally{setBusy(false);}}
 return <OwnerShell><main className="px-4 pb-10 pt-4"><div className="mb-4 flex items-center gap-2"><Link to="/owner" className="rounded-full border border-white/10 p-2 text-white/60"><ChevronLeft className="size-4"/></Link><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-blue-300">Monetization</p><h1 className="text-xl font-extrabold">Provider Control Center</h1></div></div>
 <div className="mb-4 rounded-3xl border border-blue-400/20 bg-[#121f33] p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 text-emerald-300"/><div><p className="text-sm font-bold">One place for all monetization integrations</p><p className="mt-1 text-[11px] text-slate-500">API credentials are stored server-side in Supabase Vault, not exposed to the Mini App. Signed postbacks/webhooks should be the reward authority.</p></div></div></div>
 <div className="grid grid-cols-2 gap-2">{GROUPS.map(g=>{const Icon=g.icon;return <button key={g.key} type="button" onClick={()=>setSelected(g.providers[0])} className={`rounded-2xl border p-3 text-left ${group?.key===g.key?"border-blue-400/40 bg-blue-500/10":"border-white/7 bg-[#121f33]"}`}><Icon className="size-4 text-blue-300"/><p className="mt-2 text-xs font-bold">{g.label}</p><p className="mt-0.5 text-[9px] text-slate-500">{g.providers.length} providers</p></button>})}</div>
 <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{(GROUPS.find(g=>g.key===group?.key)?.providers??[]).map(key=>{const p=providers.find(x=>x.providerKey===key);return <button key={key} type="button" onClick={()=>setSelected(key)} className={`shrink-0 rounded-full border px-3 py-2 text-[10px] font-bold ${selected===key?"border-blue-400/50 bg-blue-500/15 text-blue-200":"border-white/10 bg-[#121f33] text-slate-400"}`}>{p?.providerName??key}</button>})}</div>
 {provider?<section className="mt-4 rounded-3xl border border-white/10 bg-[#121f33] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Selected provider</p><h2 className="text-lg font-extrabold">{provider.providerName}</h2></div><label className="flex items-center gap-2 text-[10px] text-slate-400"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.checked}))}/> Enabled</label></div>
 <div className="mt-4 grid grid-cols-2 gap-2"><Field label="API Base URL" value={form.apiBaseUrl} onChange={v=>setForm(f=>({...f,apiBaseUrl:v}))} placeholder="https://api.provider.com"/><Field label="Public / App ID" value={form.publicId} onChange={v=>setForm(f=>({...f,publicId:v}))} placeholder="App / Publisher ID"/><Field label="Placement ID" value={form.placementId} onChange={v=>setForm(f=>({...f,placementId:v}))} placeholder="Placement / Zone"/><Field label="Priority" value={String(form.priority)} onChange={v=>setForm(f=>({...f,priority:Number(v)||0}))} placeholder="10"/></div>
 <div className="mt-2 grid grid-cols-2 gap-2">{secretFields.map((label,i)=><div key={label}><span className="text-[9px] font-bold uppercase tracking-wide text-slate-500">{label}</span><div className="mt-1 flex items-center rounded-2xl border border-white/10 bg-black/20 px-3"><input type={showSecret?"text":"password"} value={secretValues[String(i)]??""} onChange={e=>setSecretValues(v=>({...v,[String(i)]:e.target.value}))} placeholder="Enter secret" className="w-full bg-transparent py-3 text-xs outline-none"/>{i===0?<button type="button" onClick={()=>setShowSecret(v=>!v)} className="text-slate-500">{showSecret?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button>:null}</div></div>)}</div>
 <div className="mt-2 grid grid-cols-1 gap-2"><Field label="Postback URL" value={form.postbackUrl} onChange={v=>setForm(f=>({...f,postbackUrl:v}))} placeholder="TASKORA callback endpoint"/><Field label="Webhook URL" value={form.webhookUrl} onChange={v=>setForm(f=>({...f,webhookUrl:v}))} placeholder="Provider webhook endpoint"/></div>
 <div className="mt-2 grid grid-cols-3 gap-2"><Field label="Revenue share %" value={form.revenueSharePercent} onChange={v=>setForm(f=>({...f,revenueSharePercent:v}))} placeholder="50"/><Field label="User reward %" value={form.userRewardSharePercent} onChange={v=>setForm(f=>({...f,userRewardSharePercent:v}))} placeholder="70"/><Field label="Min payout $" value={form.minimumPayoutUsd} onChange={v=>setForm(f=>({...f,minimumPayoutUsd:v}))} placeholder="100"/></div>
 <button type="button" disabled={busy} onClick={()=>void save()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-500 px-4 py-3 text-sm font-extrabold text-white disabled:opacity-60"><Save className="size-4"/>{busy?"Saving…":"Save Provider Settings"}</button>{message?<p className="mt-3 text-center text-xs text-slate-400">{message}</p>:null}
 <div className="mt-4 rounded-2xl border border-amber-400/15 bg-amber-400/5 p-3"><div className="flex gap-2"><CircleHelp className="size-4 shrink-0 text-amber-300"/><p className="text-[10px] leading-5 text-slate-400">A configured provider is not automatically considered live. The integration adapter must support that provider's API/SDK and signed conversion/postback contract before TASKORA credits users.</p></div></div></section>:null}
 </main></OwnerShell>;
}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="block"><span className="text-[9px] font-bold uppercase tracking-wide text-slate-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-1 w-full rounded-2xl border border-white/10 bg-black/20 px-3 py-3 text-xs outline-none focus:border-blue-400/40"/></label>}
