import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronLeft, ShieldCheck } from "lucide-react";
import { getTelegramGateSettings, saveTelegramGateSettings, testTelegramGateConnection, getTelegramGateAnalytics, type TelegramGateSettings, type TelegramGateChatType } from "@/lib/telegram-gate.functions";

export const Route=createFileRoute("/_authenticated/owner/settings")({component:OwnerSettings});
function OwnerSettings(){
 const [gate,setGate]=useState<TelegramGateSettings|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[testing,setTesting]=useState(false);const[result,setResult]=useState("");const[message,setMessage]=useState("");const[analytics,setAnalytics]=useState<{total:number;verified:number;notMember:number;successRate:number}|null>(null);
 useEffect(()=>{void getTelegramGateSettings().then(setGate).catch(e=>setMessage(e instanceof Error?e.message:"Could not load settings.")).finally(()=>setLoading(false));void getTelegramGateAnalytics().then(a=>setAnalytics({total:a.total,verified:a.verified,notMember:a.notMember,successRate:a.successRate})).catch(()=>undefined)},[]);
 async function save(){if(!gate)return;setSaving(true);setMessage("");try{setGate(await saveTelegramGateSettings({data:gate}));setMessage("Telegram Gate settings saved.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save settings.")}finally{setSaving(false)}}
 async function test(){setTesting(true);setResult("");try{const r=await testTelegramGateConnection();setResult(r.ok?`✓ Connected · @${r.botUsername??"?"} · ${r.channelTitle??"?"}`:`✕ ${r.error}`)}catch(e){setResult(`✕ ${e instanceof Error?e.message:"Test failed"}`)}finally{setTesting(false)}}
 return <main className="mx-auto min-h-screen w-full max-w-md bg-[#05070c] px-4 pb-28 pt-5 text-white"><div className="mb-4 flex items-center gap-2"><Link to="/owner" className="rounded-full border border-white/10 p-2 text-white/60"><ChevronLeft className="size-4"/></Link><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-300">System</p><h1 className="text-xl font-bold">Platform Settings</h1></div></div>
 <section className="rounded-3xl border border-blue-400/15 bg-[#12141c] p-4"><div className="flex gap-3"><ShieldCheck className="size-5 text-emerald-300"/><div><p className="text-sm font-bold">Crypto payment policy</p><p className="mt-1 text-[11px] text-white/45">TASKORA payouts are crypto-only. Provider credentials belong in the secure Monetization Control Center; this page controls Telegram access and platform operations.</p></div></div></section>
 <Link to="/owner/monetization" className="mt-3 block rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4"><p className="text-sm font-bold text-amber-200">Payment & Provider Control</p><p className="mt-1 text-[11px] text-white/45">Configure OxaPay, crypto gateways, game, ad and video providers.</p></Link>
 <section className="mt-4 rounded-3xl border border-amber-300/15 bg-[#12141c] p-4"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold">Telegram Gate</h2><p className="mt-1 text-[11px] text-white/40">Require channel/group membership before app access.</p></div><button type="button" disabled={loading||!gate} onClick={()=>gate&&setGate({...gate,enabled:!gate.enabled})} className={`relative h-7 w-12 rounded-full ${gate?.enabled?"bg-amber-400":"bg-white/10"}`}><span className={`absolute top-1 size-5 rounded-full bg-white ${gate?.enabled?"left-6":"left-1"}`}/></button></div>
 {analytics?<div className="mt-3 grid grid-cols-4 gap-1.5 text-center">{[["Checks",analytics.total],["OK",analytics.verified],["Denied",analytics.notMember],["Rate",`${analytics.successRate}%`]].map(([l,v])=><div key={String(l)} className="rounded-xl border border-white/8 bg-black/20 px-1 py-2"><p className="text-[9px] uppercase text-white/40">{l}</p><p className="text-sm font-bold text-amber-300">{v}</p></div>)}</div>:null}
 {gate?<div className="mt-4 space-y-3"><Field label="Chat type" value={gate.chatType} onChange={v=>setGate({...gate,chatType:v as TelegramGateChatType})} select options={["channel","supergroup","group"]}/><Field label="Chat ID" value={gate.channelId} onChange={v=>setGate({...gate,channelId:v})} placeholder="@username or -100…"/><Field label="Join URL" value={gate.channelUrl} onChange={v=>setGate({...gate,channelUrl:v})} placeholder="https://t.me/…"/><Field label="Display name" value={gate.channelName} onChange={v=>setGate({...gate,channelName:v})}/><Field label="Gate title" value={gate.title} onChange={v=>setGate({...gate,title:v})}/><Field label="Description" value={gate.description} onChange={v=>setGate({...gate,description:v})} multiline/><Field label="Join button" value={gate.joinButtonText} onChange={v=>setGate({...gate,joinButtonText:v})}/><Field label="Check button" value={gate.checkButtonText} onChange={v=>setGate({...gate,checkButtonText:v})}/><Field label="Recheck interval" value={String(gate.checkIntervalSeconds)} onChange={v=>setGate({...gate,checkIntervalSeconds:Number(v)||300})} type="number"/><Toggle label="Admins can pass" checked={gate.allowAdmins} onChange={v=>setGate({...gate,allowAdmins:v})}/><Toggle label="Creators can pass" checked={gate.allowCreators} onChange={v=>setGate({...gate,allowCreators:v})}/><Toggle label="Members can pass" checked={gate.allowMembers} onChange={v=>setGate({...gate,allowMembers:v})}/><Toggle label="Restricted members can pass" checked={gate.allowRestricted} onChange={v=>setGate({...gate,allowRestricted:v})}/><Toggle label="Remove access after leaving" checked={gate.revokeOnLeave} onChange={v=>setGate({...gate,revokeOnLeave:v})}/><button type="button" disabled={testing} onClick={()=>void test()} className="w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-3 text-sm font-semibold">{testing?"Testing…":"TEST TELEGRAM CONNECTION"}</button>{result?<p className="text-center text-xs text-white/55">{result}</p>:null}<button type="button" disabled={saving} onClick={()=>void save()} className="w-full rounded-2xl bg-amber-400 px-4 py-3 text-sm font-extrabold text-[#05070c]">{saving?"SAVING…":"SAVE TELEGRAM GATE"}</button>{message?<p className="text-center text-xs text-white/55">{message}</p>:null}</div>:loading?<p className="mt-4 text-xs text-white/35">Loading…</p>:null}</section>
 </main>}
function Field({label,value,onChange,placeholder,select,options,multiline,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;select?:boolean;options?:string[];multiline?:boolean;type?:string}){const c="mt-1 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none";return <label className="block text-xs text-white/55">{label}{select?<select className={c} value={value} onChange={e=>onChange(e.target.value)}>{options?.map(o=><option key={o}>{o}</option>)}</select>:multiline?<textarea className={c} rows={3} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:<input className={c} type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>}</label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center justify-between rounded-xl border border-white/8 bg-black/15 px-3 py-3 text-xs text-white/65">{label}<input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="size-4 accent-amber-400"/></label>}
