import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronLeft, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { getTelegramGateSettings, saveTelegramGateSettings, previewTelegramGateChats, getTelegramGateAnalytics, type TelegramGateSettings, type TelegramGateChat } from "@/lib/telegram-gate.functions";

export const Route=createFileRoute("/_authenticated/owner/settings")({component:OwnerSettings});
const blank=(type:"channel"|"group"):TelegramGateChat=>({id:"",type,url:"",name:type==="channel"?"Telegram Channel":"Telegram Group",verified:false});
function OwnerSettings(){
 const [gate,setGate]=useState<TelegramGateSettings|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[previewing,setPreviewing]=useState(false);const[message,setMessage]=useState("");const[analytics,setAnalytics]=useState<any>(null);
 useEffect(()=>{void getTelegramGateSettings().then(g=>setGate({...g,revokeOnLeave:true,requiredChats:g.requiredChats??[]})).catch(e=>setMessage(e instanceof Error?e.message:"Could not load settings.")).finally(()=>setLoading(false));void getTelegramGateAnalytics().then(setAnalytics).catch(()=>undefined)},[]);
 const updateChat=(i:number,patch:Partial<TelegramGateChat>)=>setGate(g=>g?{...g,requiredChats:g.requiredChats.map((c,n)=>n===i?{...c,...patch}:c)}:g);
 const addChat=(type:"channel"|"group")=>setGate(g=>g?{...g,requiredChats:[...g.requiredChats,blank(type)]}:g);
 const removeChat=(i:number)=>setGate(g=>g?{...g,requiredChats:g.requiredChats.filter((_,n)=>n!==i)}:g);
 async function preview(){if(!gate)return;setPreviewing(true);setMessage("");try{const chats=await previewTelegramGateChats({data:{chats:gate.requiredChats}});setGate(g=>g?{...g,requiredChats:chats}:g);setMessage(chats.every(c=>c.verified)?"✓ Telegram verified. Live details loaded from Telegram.":"Some chats could not be read. Add the bot as administrator and check the chat ID.")}catch(e){setMessage(e instanceof Error?e.message:"Preview failed.")}finally{setPreviewing(false)}}
 async function save(){if(!gate)return;if(gate.enabled&&!gate.requiredChats.length){setMessage("Add at least one required Telegram channel/group before enabling the gate.");return}setSaving(true);setMessage("");try{setGate(await saveTelegramGateSettings({data:{...gate,revokeOnLeave:true,allowAdmins:true,allowCreators:true,allowMembers:true,allowRestricted:false}}));setMessage("✓ Saved. Every listed Telegram chat is required; leaving any one locks TASKORA.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save settings.")}finally{setSaving(false)}}
 return <main className="mx-auto min-h-screen w-full max-w-md bg-[#05070c] px-4 pb-28 pt-5 text-white"><div className="mb-4 flex items-center gap-2"><Link to="/owner" className="rounded-full border border-white/10 p-2 text-white/60"><ChevronLeft className="size-4"/></Link><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-300">System</p><h1 className="text-xl font-bold">Platform Settings</h1></div></div>
 <section className="rounded-3xl border border-blue-400/15 bg-[#12141c] p-4"><div className="flex gap-3"><ShieldCheck className="size-5 text-emerald-300"/><div><p className="text-sm font-bold">Strict Telegram Gate</p><p className="mt-1 text-[11px] leading-5 text-white/45">No whitelist, role selector, bypass list, or “who can enter” control. Access requires current membership in every Telegram chat listed below.</p></div></div></section>
 <section className="mt-4 rounded-3xl border border-amber-300/15 bg-[#12141c] p-4"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold">Gate enforcement</h2><p className="mt-1 text-[11px] text-white/40">Leave one required chat → access locks.</p></div><button type="button" disabled={!gate} onClick={()=>gate&&setGate({...gate,enabled:!gate.enabled})} className={`relative h-7 w-12 rounded-full ${gate?.enabled?"bg-amber-400":"bg-white/10"}`}><span className={`absolute top-1 size-5 rounded-full bg-white ${gate?.enabled?"left-6":"left-1"}`}/></button></div><div className="mt-3 rounded-2xl border border-emerald-400/15 bg-emerald-400/5 p-3"><p className="text-xs font-bold text-emerald-300">Live membership verification</p><p className="mt-1 text-[10px] leading-5 text-white/45">TASKORA performs a fresh Telegram membership check while the Mini App is open. The bot must be an administrator for reliable membership checks.</p></div></section>
 <section className="mt-4 rounded-3xl border border-white/10 bg-[#12141c] p-4"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold">Required Telegram communities</h2><p className="mt-1 text-[11px] text-white/40">Add the official channel, group, or both.</p></div><div className="flex gap-1"><button type="button" onClick={()=>addChat("channel")} className="rounded-xl border border-white/10 px-2 py-2 text-[10px]"><Plus className="mr-1 inline size-3"/>Channel</button><button type="button" onClick={()=>addChat("group")} className="rounded-xl border border-white/10 px-2 py-2 text-[10px]"><Plus className="mr-1 inline size-3"/>Group</button></div></div>
 {gate?.requiredChats.map((c,i)=><div key={`${i}-${c.id}`} className="mt-3 rounded-2xl border border-white/10 bg-black/20 p-3"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">{c.type==='channel'?'📢 Channel':'👥 Group'} {i+1}</p>{c.verified?<p className="text-[9px] text-emerald-300">✓ Verified by Telegram</p>:<p className="text-[9px] text-white/35">Not verified yet</p>}</div><button type="button" onClick={()=>removeChat(i)} className="rounded-lg p-2 text-red-300/70"><Trash2 className="size-4"/></button></div><Field label="Chat ID or @username" value={c.id} onChange={v=>updateChat(i,{id:v,verified:false})} placeholder="@taskora_channel or -100…"/><Field label="Join URL" value={c.url} onChange={v=>updateChat(i,{url:v})} placeholder="https://t.me/…"/>{c.verified?<div className="mt-2 rounded-xl border border-emerald-400/10 bg-emerald-400/5 p-3"><p className="text-sm font-bold">{c.name}</p><p className="mt-1 text-[10px] text-white/45">{c.username?`@${c.username} · `:""}{c.memberCount==null?"Member count unavailable":`${c.memberCount.toLocaleString()} members`}</p>{c.description?<p className="mt-2 text-[10px] leading-4 text-white/40">{c.description}</p>:null}</div>:null}</div>)}
 {!gate?.requiredChats.length?<div className="mt-3 rounded-2xl border border-dashed border-white/10 p-5 text-center text-[11px] text-white/35">No required chat added yet.</div>:null}<button type="button" disabled={previewing||!gate?.requiredChats.length} onClick={()=>void preview()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl border border-blue-400/20 bg-blue-400/10 px-4 py-3 text-xs font-bold text-blue-200"><RefreshCw className={`size-4 ${previewing?"animate-spin":""}`}/>{previewing?"Loading real Telegram details…":"VERIFY & LOAD TELEGRAM PREVIEW"}</button></section>
 <section className="mt-4 rounded-3xl border border-white/10 bg-[#12141c] p-4"><h2 className="text-base font-bold">Gate message</h2>{gate?<div className="mt-3 space-y-3"><Field label="Title" value={gate.title} onChange={v=>setGate({...gate,title:v})}/><Field label="Description" value={gate.description} onChange={v=>setGate({...gate,description:v})} multiline/><Field label="Join button" value={gate.joinButtonText} onChange={v=>setGate({...gate,joinButtonText:v})}/><Field label="Check button" value={gate.checkButtonText} onChange={v=>setGate({...gate,checkButtonText:v})}/></div>:null}</section>
 {analytics?<section className="mt-4 grid grid-cols-4 gap-1.5 text-center">{[["Checks",analytics.total],["OK",analytics.verified],["Denied",analytics.notMember],["Rate",`${analytics.successRate}%`]].map(([l,v])=><div key={String(l)} className="rounded-xl border border-white/8 bg-[#12141c] px-1 py-2"><p className="text-[9px] uppercase text-white/40">{l}</p><p className="text-sm font-bold text-amber-300">{v}</p></div>)}</section>:null}
 <button type="button" disabled={saving||!gate} onClick={()=>void save()} className="mt-4 w-full rounded-2xl bg-amber-400 px-4 py-3 text-sm font-extrabold text-[#05070c]">{saving?"SAVING…":"SAVE STRICT TELEGRAM GATE"}</button>{message?<p className="mt-3 text-center text-xs text-white/55">{message}</p>:null}<Link to="/owner/monetization" className="mt-4 block rounded-2xl border border-blue-400/15 bg-blue-400/5 p-4"><p className="text-sm font-bold text-blue-200">Provider Control Center →</p><p className="mt-1 text-[10px] text-white/40">Configure API keys, secrets, publisher IDs, placement IDs, webhooks and reward shares for every provider.</p></Link>
 </main>}
function Field({label,value,onChange,placeholder,multiline}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;multiline?:boolean}){const c="mt-1 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none";return <label className="block text-xs text-white/55">{label}{multiline?<textarea className={c} rows={3} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:<input className={c} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>}</label>}
