/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TelegramGateRouteImport } from './routes/telegram-gate'
import { Route as AuthenticatedAdvertiseRouteImport } from './routes/_authenticated/advertise'
import { Route as AuthenticatedAmbassadorRouteImport } from './routes/_authenticated/ambassador'
import { Route as AuthenticatedConnectedRouteImport } from './routes/_authenticated/connected'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedWatchEarnRouteImport } from './routes/_authenticated/watch-earn'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedOwnerAnalyticsRouteImport } from './routes/_authenticated/owner.analytics'
import { Route as AuthenticatedOwnerAnnounceRouteImport } from './routes/_authenticated/owner.announce'
import { Route as AuthenticatedOwnerAuditRouteImport } from './routes/_authenticated/owner.audit'
import { Route as AuthenticatedOwnerCampaignsRouteImport } from './routes/_authenticated/owner.campaigns'
import { Route as AuthenticatedOwnerConnectedRouteImport } from './routes/_authenticated/owner.connected'
import { Route as AuthenticatedOwnerDepositsRouteImport } from './routes/_authenticated/owner.deposits'
import { Route as AuthenticatedOwnerDocumentsRouteImport } from './routes/_authenticated/owner.documents'
import { Route as AuthenticatedOwnerEconomyRouteImport } from './routes/_authenticated/owner.economy'
import { Route as AuthenticatedOwnerFlagsRouteImport } from './routes/_authenticated/owner.flags'
import { Route as AuthenticatedOwnerFraudRouteImport } from './routes/_authenticated/owner.fraud'
import { Route as AuthenticatedOwnerHealthRouteImport } from './routes/_authenticated/owner.health'
import { Route as AuthenticatedOwnerLedgerRouteImport } from './routes/_authenticated/owner.ledger'
import { Route as AuthenticatedOwnerMonetizationRouteImport } from './routes/_authenticated/owner.monetization'
import { Route as AuthenticatedOwnerPaymentSettingsRouteImport } from './routes/_authenticated/owner/payment-settings'
import { Route as AuthenticatedOwnerReviewsRouteImport } from './routes/_authenticated/owner.reviews'
import { Route as AuthenticatedOwnerRolesRouteImport } from './routes/_authenticated/owner.roles'
import { Route as AuthenticatedOwnerSettingsRouteImport } from './routes/_authenticated/owner.settings'
import { Route as AuthenticatedOwnerTasksRouteImport } from './routes/_authenticated/owner.tasks'
import { Route as AuthenticatedOwnerTicketsRouteImport } from './routes/_authenticated/owner.tickets'
import { Route as AuthenticatedOwnerUsersRouteImport } from './routes/_authenticated/owner.users'
import { Route as AuthenticatedOwnerVideosRouteImport } from './routes/_authenticated/owner.videos'
import { Route as AuthenticatedOwnerWelcomeRouteImport } from './routes/_authenticated/owner.welcome'
import { Route as AuthenticatedOwnerWithdrawalsRouteImport } from './routes/_authenticated/owner.withdrawals'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramGateRoute = TelegramGateRouteImport.update({
  id: '/telegram-gate',
  path: '/telegram-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdvertiseRoute = AuthenticatedAdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmbassadorRoute = AuthenticatedAmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectedRoute = AuthenticatedConnectedRouteImport.update({
  id: '/connected',
  path: '/connected',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchEarnRoute = AuthenticatedWatchEarnRouteImport.update({
  id: '/watch-earn',
  path: '/watch-earn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerAnalyticsRoute =
  AuthenticatedOwnerAnalyticsRouteImport.update({
    id: '/owner/analytics',
    path: '/owner/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerAnnounceRoute =
  AuthenticatedOwnerAnnounceRouteImport.update({
    id: '/owner/announce',
    path: '/owner/announce',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerAuditRoute = AuthenticatedOwnerAuditRouteImport.update({
  id: '/owner/audit',
  path: '/owner/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerCampaignsRoute =
  AuthenticatedOwnerCampaignsRouteImport.update({
    id: '/owner/campaigns',
    path: '/owner/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerConnectedRoute =
  AuthenticatedOwnerConnectedRouteImport.update({
    id: '/owner/connected',
    path: '/owner/connected',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerDepositsRoute =
  AuthenticatedOwnerDepositsRouteImport.update({
    id: '/owner/deposits',
    path: '/owner/deposits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerDocumentsRoute =
  AuthenticatedOwnerDocumentsRouteImport.update({
    id: '/owner/documents',
    path: '/owner/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerEconomyRoute =
  AuthenticatedOwnerEconomyRouteImport.update({
    id: '/owner/economy',
    path: '/owner/economy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerFlagsRoute = AuthenticatedOwnerFlagsRouteImport.update({
  id: '/owner/flags',
  path: '/owner/flags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerFraudRoute = AuthenticatedOwnerFraudRouteImport.update({
  id: '/owner/fraud',
  path: '/owner/fraud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerHealthRoute =
  AuthenticatedOwnerHealthRouteImport.update({
    id: '/owner/health',
    path: '/owner/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerLedgerRoute =
  AuthenticatedOwnerLedgerRouteImport.update({
    id: '/owner/ledger',
    path: '/owner/ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerMonetizationRoute =
  AuthenticatedOwnerMonetizationRouteImport.update({
    id: '/owner/monetization',
    path: '/owner/monetization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerPaymentSettingsRoute =
  AuthenticatedOwnerPaymentSettingsRouteImport.update({
    id: '/owner/payment-settings',
    path: '/owner/payment-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerReviewsRoute =
  AuthenticatedOwnerReviewsRouteImport.update({
    id: '/owner/reviews',
    path: '/owner/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerRolesRoute = AuthenticatedOwnerRolesRouteImport.update({
  id: '/owner/roles',
  path: '/owner/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerSettingsRoute =
  AuthenticatedOwnerSettingsRouteImport.update({
    id: '/owner/settings',
    path: '/owner/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerTasksRoute = AuthenticatedOwnerTasksRouteImport.update({
  id: '/owner/tasks',
  path: '/owner/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerTicketsRoute =
  AuthenticatedOwnerTicketsRouteImport.update({
    id: '/owner/tickets',
    path: '/owner/tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerUsersRoute = AuthenticatedOwnerUsersRouteImport.update({
  id: '/owner/users',
  path: '/owner/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerVideosRoute =
  AuthenticatedOwnerVideosRouteImport.update({
    id: '/owner/videos',
    path: '/owner/videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerWelcomeRoute =
  AuthenticatedOwnerWelcomeRouteImport.update({
    id: '/owner/welcome',
    path: '/owner/welcome',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerWithdrawalsRoute =
  AuthenticatedOwnerWithdrawalsRouteImport.update({
    id: '/owner/withdrawals',
    path: '/owner/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/telegram-gate': typeof TelegramGateRoute
  '/advertise': typeof AuthenticatedAdvertiseRoute
  '/ambassador': typeof AuthenticatedAmbassadorRoute
  '/connected': typeof AuthenticatedConnectedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/watch-earn': typeof AuthenticatedWatchEarnRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/announce': typeof AuthenticatedOwnerAnnounceRoute
  '/owner/audit': typeof AuthenticatedOwnerAuditRoute
  '/owner/campaigns': typeof AuthenticatedOwnerCampaignsRoute
  '/owner/connected': typeof AuthenticatedOwnerConnectedRoute
  '/owner/deposits': typeof AuthenticatedOwnerDepositsRoute
  '/owner/documents': typeof AuthenticatedOwnerDocumentsRoute
  '/owner/economy': typeof AuthenticatedOwnerEconomyRoute
  '/owner/flags': typeof AuthenticatedOwnerFlagsRoute
  '/owner/fraud': typeof AuthenticatedOwnerFraudRoute
  '/owner/health': typeof AuthenticatedOwnerHealthRoute
  '/owner/ledger': typeof AuthenticatedOwnerLedgerRoute
  '/owner/monetization': typeof AuthenticatedOwnerMonetizationRoute
  '/owner/payment-settings': typeof AuthenticatedOwnerPaymentSettingsRoute
  '/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/owner/roles': typeof AuthenticatedOwnerRolesRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/tasks': typeof AuthenticatedOwnerTasksRoute
  '/owner/tickets': typeof AuthenticatedOwnerTicketsRoute
  '/owner/users': typeof AuthenticatedOwnerUsersRoute
  '/owner/videos': typeof AuthenticatedOwnerVideosRoute
  '/owner/welcome': typeof AuthenticatedOwnerWelcomeRoute
  '/owner/withdrawals': typeof AuthenticatedOwnerWithdrawalsRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/telegram-gate': typeof TelegramGateRoute
  '/advertise': typeof AuthenticatedAdvertiseRoute
  '/ambassador': typeof AuthenticatedAmbassadorRoute
  '/connected': typeof AuthenticatedConnectedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/watch-earn': typeof AuthenticatedWatchEarnRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/announce': typeof AuthenticatedOwnerAnnounceRoute
  '/owner/audit': typeof AuthenticatedOwnerAuditRoute
  '/owner/campaigns': typeof AuthenticatedOwnerCampaignsRoute
  '/owner/connected': typeof AuthenticatedOwnerConnectedRoute
  '/owner/deposits': typeof AuthenticatedOwnerDepositsRoute
  '/owner/documents': typeof AuthenticatedOwnerDocumentsRoute
  '/owner/economy': typeof AuthenticatedOwnerEconomyRoute
  '/owner/flags': typeof AuthenticatedOwnerFlagsRoute
  '/owner/fraud': typeof AuthenticatedOwnerFraudRoute
  '/owner/health': typeof AuthenticatedOwnerHealthRoute
  '/owner/ledger': typeof AuthenticatedOwnerLedgerRoute
  '/owner/monetization': typeof AuthenticatedOwnerMonetizationRoute
  '/owner/payment-settings': typeof AuthenticatedOwnerPaymentSettingsRoute
  '/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/owner/roles': typeof AuthenticatedOwnerRolesRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/tasks': typeof AuthenticatedOwnerTasksRoute
  '/owner/tickets': typeof AuthenticatedOwnerTicketsRoute
  '/owner/users': typeof AuthenticatedOwnerUsersRoute
  '/owner/videos': typeof AuthenticatedOwnerVideosRoute
  '/owner/welcome': typeof AuthenticatedOwnerWelcomeRoute
  '/owner/withdrawals': typeof AuthenticatedOwnerWithdrawalsRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/telegram-gate': typeof TelegramGateRoute
  '/_authenticated/advertise': typeof AuthenticatedAdvertiseRoute
  '/_authenticated/ambassador': typeof AuthenticatedAmbassadorRoute
  '/_authenticated/connected': typeof AuthenticatedConnectedRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/watch-earn': typeof AuthenticatedWatchEarnRoute
  '/_authenticated/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/_authenticated/owner/announce': typeof AuthenticatedOwnerAnnounceRoute
  '/_authenticated/owner/audit': typeof AuthenticatedOwnerAuditRoute
  '/_authenticated/owner/campaigns': typeof AuthenticatedOwnerCampaignsRoute
  '/_authenticated/owner/connected': typeof AuthenticatedOwnerConnectedRoute
  '/_authenticated/owner/deposits': typeof AuthenticatedOwnerDepositsRoute
  '/_authenticated/owner/documents': typeof AuthenticatedOwnerDocumentsRoute
  '/_authenticated/owner/economy': typeof AuthenticatedOwnerEconomyRoute
  '/_authenticated/owner/flags': typeof AuthenticatedOwnerFlagsRoute
  '/_authenticated/owner/fraud': typeof AuthenticatedOwnerFraudRoute
  '/_authenticated/owner/health': typeof AuthenticatedOwnerHealthRoute
  '/_authenticated/owner/ledger': typeof AuthenticatedOwnerLedgerRoute
  '/_authenticated/owner/monetization': typeof AuthenticatedOwnerMonetizationRoute
  '/_authenticated/owner/payment-settings': typeof AuthenticatedOwnerPaymentSettingsRoute
  '/_authenticated/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/_authenticated/owner/roles': typeof AuthenticatedOwnerRolesRoute
  '/_authenticated/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/_authenticated/owner/tasks': typeof AuthenticatedOwnerTasksRoute
  '/_authenticated/owner/tickets': typeof AuthenticatedOwnerTicketsRoute
  '/_authenticated/owner/users': typeof AuthenticatedOwnerUsersRoute
  '/_authenticated/owner/videos': typeof AuthenticatedOwnerVideosRoute
  '/_authenticated/owner/welcome': typeof AuthenticatedOwnerWelcomeRoute
  '/_authenticated/owner/withdrawals': typeof AuthenticatedOwnerWithdrawalsRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/telegram-gate'
    | '/advertise'
    | '/ambassador'
    | '/connected'
    | '/home'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/wallet'
    | '/watch-earn'
    | '/owner/analytics'
    | '/owner/announce'
    | '/owner/audit'
    | '/owner/campaigns'
    | '/owner/connected'
    | '/owner/deposits'
    | '/owner/documents'
    | '/owner/economy'
    | '/owner/flags'
    | '/owner/fraud'
    | '/owner/health'
    | '/owner/ledger'
    | '/owner/monetization'
    | '/owner/payment-settings'
    | '/owner/reviews'
    | '/owner/roles'
    | '/owner/settings'
    | '/owner/tasks'
    | '/owner/tickets'
    | '/owner/users'
    | '/owner/videos'
    | '/owner/welcome'
    | '/owner/withdrawals'
    | '/tasks/$taskId'
    | '/owner/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/telegram-gate'
    | '/advertise'
    | '/ambassador'
    | '/connected'
    | '/home'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/wallet'
    | '/watch-earn'
    | '/owner/analytics'
    | '/owner/announce'
    | '/owner/audit'
    | '/owner/campaigns'
    | '/owner/connected'
    | '/owner/deposits'
    | '/owner/documents'
    | '/owner/economy'
    | '/owner/flags'
    | '/owner/fraud'
    | '/owner/health'
    | '/owner/ledger'
    | '/owner/monetization'
    | '/owner/payment-settings'
    | '/owner/reviews'
    | '/owner/roles'
    | '/owner/settings'
    | '/owner/tasks'
    | '/owner/tickets'
    | '/owner/users'
    | '/owner/videos'
    | '/owner/welcome'
    | '/owner/withdrawals'
    | '/tasks/$taskId'
    | '/owner'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/telegram-gate'
    | '/_authenticated/advertise'
    | '/_authenticated/ambassador'
    | '/_authenticated/connected'
    | '/_authenticated/home'
    | '/_authenticated/leaderboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/support'
    | '/_authenticated/wallet'
    | '/_authenticated/watch-earn'
    | '/_authenticated/owner/analytics'
    | '/_authenticated/owner/announce'
    | '/_authenticated/owner/audit'
    | '/_authenticated/owner/campaigns'
    | '/_authenticated/owner/connected'
    | '/_authenticated/owner/deposits'
    | '/_authenticated/owner/documents'
    | '/_authenticated/owner/economy'
    | '/_authenticated/owner/flags'
    | '/_authenticated/owner/fraud'
    | '/_authenticated/owner/health'
    | '/_authenticated/owner/ledger'
    | '/_authenticated/owner/monetization'
    | '/_authenticated/owner/payment-settings'
    | '/_authenticated/owner/reviews'
    | '/_authenticated/owner/roles'
    | '/_authenticated/owner/settings'
    | '/_authenticated/owner/tasks'
    | '/_authenticated/owner/tickets'
    | '/_authenticated/owner/users'
    | '/_authenticated/owner/videos'
    | '/_authenticated/owner/welcome'
    | '/_authenticated/owner/withdrawals'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/owner/'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TelegramGateRoute: typeof TelegramGateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram-gate': {
      id: '/telegram-gate'
      path: '/telegram-gate'
      fullPath: '/telegram-gate'
      preLoaderRoute: typeof TelegramGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advertise': {
      id: '/_authenticated/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AuthenticatedAdvertiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ambassador': {
      id: '/_authenticated/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AuthenticatedAmbassadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connected': {
      id: '/_authenticated/connected'
      path: '/connected'
      fullPath: '/connected'
      preLoaderRoute: typeof AuthenticatedConnectedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch-earn': {
      id: '/_authenticated/watch-earn'
      path: '/watch-earn'
      fullPath: '/watch-earn'
      preLoaderRoute: typeof AuthenticatedWatchEarnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/analytics': {
      id: '/_authenticated/owner/analytics'
      path: '/owner/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof AuthenticatedOwnerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/announce': {
      id: '/_authenticated/owner/announce'
      path: '/owner/announce'
      fullPath: '/owner/announce'
      preLoaderRoute: typeof AuthenticatedOwnerAnnounceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/audit': {
      id: '/_authenticated/owner/audit'
      path: '/owner/audit'
      fullPath: '/owner/audit'
      preLoaderRoute: typeof AuthenticatedOwnerAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/campaigns': {
      id: '/_authenticated/owner/campaigns'
      path: '/owner/campaigns'
      fullPath: '/owner/campaigns'
      preLoaderRoute: typeof AuthenticatedOwnerCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/connected': {
      id: '/_authenticated/owner/connected'
      path: '/owner/connected'
      fullPath: '/owner/connected'
      preLoaderRoute: typeof AuthenticatedOwnerConnectedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/deposits': {
      id: '/_authenticated/owner/deposits'
      path: '/owner/deposits'
      fullPath: '/owner/deposits'
      preLoaderRoute: typeof AuthenticatedOwnerDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/documents': {
      id: '/_authenticated/owner/documents'
      path: '/owner/documents'
      fullPath: '/owner/documents'
      preLoaderRoute: typeof AuthenticatedOwnerDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/economy': {
      id: '/_authenticated/owner/economy'
      path: '/owner/economy'
      fullPath: '/owner/economy'
      preLoaderRoute: typeof AuthenticatedOwnerEconomyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/flags': {
      id: '/_authenticated/owner/flags'
      path: '/owner/flags'
      fullPath: '/owner/flags'
      preLoaderRoute: typeof AuthenticatedOwnerFlagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/fraud': {
      id: '/_authenticated/owner/fraud'
      path: '/owner/fraud'
      fullPath: '/owner/fraud'
      preLoaderRoute: typeof AuthenticatedOwnerFraudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/health': {
      id: '/_authenticated/owner/health'
      path: '/owner/health'
      fullPath: '/owner/health'
      preLoaderRoute: typeof AuthenticatedOwnerHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/ledger': {
      id: '/_authenticated/owner/ledger'
      path: '/owner/ledger'
      fullPath: '/owner/ledger'
      preLoaderRoute: typeof AuthenticatedOwnerLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/monetization': {
      id: '/_authenticated/owner/monetization'
      path: '/owner/monetization'
      fullPath: '/owner/monetization'
      preLoaderRoute: typeof AuthenticatedOwnerMonetizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/payment-settings': {
      id: '/_authenticated/owner/payment-settings'
      path: '/owner/payment-settings'
      fullPath: '/owner/payment-settings'
      preLoaderRoute: typeof AuthenticatedOwnerPaymentSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/reviews': {
      id: '/_authenticated/owner/reviews'
      path: '/owner/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof AuthenticatedOwnerReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/roles': {
      id: '/_authenticated/owner/roles'
      path: '/owner/roles'
      fullPath: '/owner/roles'
      preLoaderRoute: typeof AuthenticatedOwnerRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/settings': {
      id: '/_authenticated/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof AuthenticatedOwnerSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/tasks': {
      id: '/_authenticated/owner/tasks'
      path: '/owner/tasks'
      fullPath: '/owner/tasks'
      preLoaderRoute: typeof AuthenticatedOwnerTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/tickets': {
      id: '/_authenticated/owner/tickets'
      path: '/owner/tickets'
      fullPath: '/owner/tickets'
      preLoaderRoute: typeof AuthenticatedOwnerTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/users': {
      id: '/_authenticated/owner/users'
      path: '/owner/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof AuthenticatedOwnerUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/videos': {
      id: '/_authenticated/owner/videos'
      path: '/owner/videos'
      fullPath: '/owner/videos'
      preLoaderRoute: typeof AuthenticatedOwnerVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/welcome': {
      id: '/_authenticated/owner/welcome'
      path: '/owner/welcome'
      fullPath: '/owner/welcome'
      preLoaderRoute: typeof AuthenticatedOwnerWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/withdrawals': {
      id: '/_authenticated/owner/withdrawals'
      path: '/owner/withdrawals'
      fullPath: '/owner/withdrawals'
      preLoaderRoute: typeof AuthenticatedOwnerWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdvertiseRoute: typeof AuthenticatedAdvertiseRoute
  AuthenticatedAmbassadorRoute: typeof AuthenticatedAmbassadorRoute
  AuthenticatedConnectedRoute: typeof AuthenticatedConnectedRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWatchEarnRoute: typeof AuthenticatedWatchEarnRoute
  AuthenticatedOwnerAnalyticsRoute: typeof AuthenticatedOwnerAnalyticsRoute
  AuthenticatedOwnerAnnounceRoute: typeof AuthenticatedOwnerAnnounceRoute
  AuthenticatedOwnerAuditRoute: typeof AuthenticatedOwnerAuditRoute
  AuthenticatedOwnerCampaignsRoute: typeof AuthenticatedOwnerCampaignsRoute
  AuthenticatedOwnerConnectedRoute: typeof AuthenticatedOwnerConnectedRoute
  AuthenticatedOwnerDepositsRoute: typeof AuthenticatedOwnerDepositsRoute
  AuthenticatedOwnerDocumentsRoute: typeof AuthenticatedOwnerDocumentsRoute
  AuthenticatedOwnerEconomyRoute: typeof AuthenticatedOwnerEconomyRoute
  AuthenticatedOwnerFlagsRoute: typeof AuthenticatedOwnerFlagsRoute
  AuthenticatedOwnerFraudRoute: typeof AuthenticatedOwnerFraudRoute
  AuthenticatedOwnerHealthRoute: typeof AuthenticatedOwnerHealthRoute
  AuthenticatedOwnerLedgerRoute: typeof AuthenticatedOwnerLedgerRoute
  AuthenticatedOwnerMonetizationRoute: typeof AuthenticatedOwnerMonetizationRoute
  AuthenticatedOwnerPaymentSettingsRoute: typeof AuthenticatedOwnerPaymentSettingsRoute
  AuthenticatedOwnerReviewsRoute: typeof AuthenticatedOwnerReviewsRoute
  AuthenticatedOwnerRolesRoute: typeof AuthenticatedOwnerRolesRoute
  AuthenticatedOwnerSettingsRoute: typeof AuthenticatedOwnerSettingsRoute
  AuthenticatedOwnerTasksRoute: typeof AuthenticatedOwnerTasksRoute
  AuthenticatedOwnerTicketsRoute: typeof AuthenticatedOwnerTicketsRoute
  AuthenticatedOwnerUsersRoute: typeof AuthenticatedOwnerUsersRoute
  AuthenticatedOwnerVideosRoute: typeof AuthenticatedOwnerVideosRoute
  AuthenticatedOwnerWelcomeRoute: typeof AuthenticatedOwnerWelcomeRoute
  AuthenticatedOwnerWithdrawalsRoute: typeof AuthenticatedOwnerWithdrawalsRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdvertiseRoute: AuthenticatedAdvertiseRoute,
  AuthenticatedAmbassadorRoute: AuthenticatedAmbassadorRoute,
  AuthenticatedConnectedRoute: AuthenticatedConnectedRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWatchEarnRoute: AuthenticatedWatchEarnRoute,
  AuthenticatedOwnerAnalyticsRoute: AuthenticatedOwnerAnalyticsRoute,
  AuthenticatedOwnerAnnounceRoute: AuthenticatedOwnerAnnounceRoute,
  AuthenticatedOwnerAuditRoute: AuthenticatedOwnerAuditRoute,
  AuthenticatedOwnerCampaignsRoute: AuthenticatedOwnerCampaignsRoute,
  AuthenticatedOwnerConnectedRoute: AuthenticatedOwnerConnectedRoute,
  AuthenticatedOwnerDepositsRoute: AuthenticatedOwnerDepositsRoute,
  AuthenticatedOwnerDocumentsRoute: AuthenticatedOwnerDocumentsRoute,
  AuthenticatedOwnerEconomyRoute: AuthenticatedOwnerEconomyRoute,
  AuthenticatedOwnerFlagsRoute: AuthenticatedOwnerFlagsRoute,
  AuthenticatedOwnerFraudRoute: AuthenticatedOwnerFraudRoute,
  AuthenticatedOwnerHealthRoute: AuthenticatedOwnerHealthRoute,
  AuthenticatedOwnerLedgerRoute: AuthenticatedOwnerLedgerRoute,
  AuthenticatedOwnerMonetizationRoute: AuthenticatedOwnerMonetizationRoute,
  AuthenticatedOwnerPaymentSettingsRoute:
    AuthenticatedOwnerPaymentSettingsRoute,
  AuthenticatedOwnerReviewsRoute: AuthenticatedOwnerReviewsRoute,
  AuthenticatedOwnerRolesRoute: AuthenticatedOwnerRolesRoute,
  AuthenticatedOwnerSettingsRoute: AuthenticatedOwnerSettingsRoute,
  AuthenticatedOwnerTasksRoute: AuthenticatedOwnerTasksRoute,
  AuthenticatedOwnerTicketsRoute: AuthenticatedOwnerTicketsRoute,
  AuthenticatedOwnerUsersRoute: AuthenticatedOwnerUsersRoute,
  AuthenticatedOwnerVideosRoute: AuthenticatedOwnerVideosRoute,
  AuthenticatedOwnerWelcomeRoute: AuthenticatedOwnerWelcomeRoute,
  AuthenticatedOwnerWithdrawalsRoute: AuthenticatedOwnerWithdrawalsRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TelegramGateRoute: TelegramGateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
