-- B: advertiser funding and campaign budget controls
create table if not exists public.advertiser_funding_accounts (advertiser_id uuid primary key references public.profiles(id) on delete cascade, available_balance numeric(20,8) not null default 0 check (available_balance>=0), reserved_balance numeric(20,8) not null default 0 check (reserved_balance>=0), spent_balance numeric(20,8) not null default 0 check (spent_balance>=0), updated_at timestamptz not null default now());
create table if not exists public.advertiser_funding_ledger (id uuid primary key default gen_random_uuid(), advertiser_id uuid not null references public.profiles(id) on delete cascade, campaign_id uuid references public.campaigns(id) on delete set null, deposit_id uuid references public.deposits(id) on delete set null, entry_type text not null check(entry_type in('deposit_credit','campaign_reserve','campaign_spend','campaign_release','campaign_refund','manual_adjustment')), amount numeric(20,8) not null check(amount>0), currency text not null default 'USD', reference text not null, meta jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(deposit_id,entry_type));
alter table public.campaigns add column if not exists funding_status text not null default 'unfunded' check(funding_status in('unfunded','funded','depleted','released','refunded'));
alter table public.campaigns add column if not exists funding_reserved numeric(20,8) not null default 0;
alter table public.campaigns add column if not exists funding_spent numeric(20,8) not null default 0;
create index if not exists advertiser_funding_ledger_advertiser_idx on public.advertiser_funding_ledger(advertiser_id,created_at desc);
create index if not exists advertiser_funding_ledger_campaign_idx on public.advertiser_funding_ledger(campaign_id,created_at desc);
alter table public.advertiser_funding_accounts enable row level security;
alter table public.advertiser_funding_ledger enable row level security;
drop policy if exists "advertiser funding own read" on public.advertiser_funding_accounts;
create policy "advertiser funding own read" on public.advertiser_funding_accounts for select to authenticated using((select auth.uid())=advertiser_id);
drop policy if exists "advertiser funding ledger own read" on public.advertiser_funding_ledger;
create policy "advertiser funding ledger own read" on public.advertiser_funding_ledger for select to authenticated using((select auth.uid())=advertiser_id);
create or replace function public.credit_advertiser_deposit(p_deposit_id uuid,p_advertiser_id uuid,p_amount numeric) returns numeric language plpgsql security definer set search_path='' as $$
declare v numeric; begin if p_amount<=0 then raise exception 'Deposit amount must be positive'; end if; insert into public.advertiser_funding_accounts(advertiser_id) values(p_advertiser_id) on conflict do nothing; perform 1 from public.advertiser_funding_accounts where advertiser_id=p_advertiser_id for update; if exists(select 1 from public.advertiser_funding_ledger where deposit_id=p_deposit_id and entry_type='deposit_credit') then select available_balance into v from public.advertiser_funding_accounts where advertiser_id=p_advertiser_id; return v; end if; update public.advertiser_funding_accounts set available_balance=available_balance+p_amount,updated_at=now() where advertiser_id=p_advertiser_id returning available_balance into v; insert into public.advertiser_funding_ledger(advertiser_id,deposit_id,entry_type,amount,reference) values(p_advertiser_id,p_deposit_id,'deposit_credit',p_amount,'deposit:'||p_deposit_id::text); return v; end $$;
create or replace function public.reserve_campaign_budget(p_advertiser_id uuid,p_campaign_id uuid,p_amount numeric) returns numeric language plpgsql security definer set search_path='' as $$
declare v numeric; begin if p_amount<=0 then raise exception 'Campaign budget must be positive'; end if; insert into public.advertiser_funding_accounts(advertiser_id) values(p_advertiser_id) on conflict do nothing; perform 1 from public.advertiser_funding_accounts where advertiser_id=p_advertiser_id for update; select available_balance into v from public.advertiser_funding_accounts where advertiser_id=p_advertiser_id; if v<p_amount then raise exception 'Insufficient advertiser balance. Deposit funds before publishing this campaign.'; end if; update public.advertiser_funding_accounts set available_balance=available_balance-p_amount,reserved_balance=reserved_balance+p_amount,updated_at=now() where advertiser_id=p_advertiser_id; insert into public.advertiser_funding_ledger(advertiser_id,campaign_id,entry_type,amount,reference) values(p_advertiser_id,p_campaign_id,'campaign_reserve',p_amount,'campaign:'||p_campaign_id::text); update public.campaigns set funding_status='funded',funding_reserved=p_amount,funding_spent=0,updated_at=now() where id=p_campaign_id and advertiser_user_id=p_advertiser_id; return v-p_amount; end $$;
create or replace function public.release_campaign_budget(p_campaign_id uuid) returns numeric language plpgsql security definer set search_path='' as $$
declare c public.campaigns%rowtype; r numeric; v numeric; begin select * into c from public.campaigns where id=p_campaign_id for update; if not found then raise exception 'Campaign not found'; end if; r:=greatest(0,coalesce(c.funding_reserved,0)-coalesce(c.funding_spent,0)); if r=0 then return 0; end if; perform 1 from public.advertiser_funding_accounts where advertiser_id=c.advertiser_user_id for update; update public.advertiser_funding_accounts set reserved_balance=greatest(0,reserved_balance-r),available_balance=available_balance+r,updated_at=now() where advertiser_id=c.advertiser_user_id returning available_balance into v; insert into public.advertiser_funding_ledger(advertiser_id,campaign_id,entry_type,amount,reference) values(c.advertiser_user_id,p_campaign_id,'campaign_release',r,'campaign-release:'||gen_random_uuid()::text); update public.campaigns set funding_status='released',funding_reserved=funding_spent,updated_at=now() where id=p_campaign_id; return coalesce(v,0); end $$;
revoke execute on function public.credit_advertiser_deposit(uuid,uuid,numeric) from public,anon,authenticated;
revoke execute on function public.reserve_campaign_budget(uuid,uuid,numeric) from public,anon,authenticated;
revoke execute on function public.release_campaign_budget(uuid) from public,anon,authenticated;