-- TASKORA production-data cleanup.
-- The initial schema migration inserted sample/demo marketplace tasks. Remove
-- those records so the Telegram Mini App starts with an empty real marketplace.

DELETE FROM public.submissions
WHERE task_id IN (
  SELECT id FROM public.tasks
  WHERE title IN (
    'Join the Alpha Signals channel',
    'Watch & like the launch video',
    'Follow @taskora and repost the pinned post',
    'Join the merchant community group',
    'Follow the creator account',
    'Join the community server',
    'Follow and save the brand post'
  )
  AND advertiser IN (
    'Alpha Signals',
    'Nova Wallet',
    'TASKORA',
    'PayLink Africa',
    'Loop Studio',
    'Zenith Labs',
    'Aurum Wear'
  )
);

DELETE FROM public.tasks
WHERE title IN (
  'Join the Alpha Signals channel',
  'Watch & like the launch video',
  'Follow @taskora and repost the pinned post',
  'Join the merchant community group',
  'Follow the creator account',
  'Join the community server',
  'Follow and save the brand post'
)
AND advertiser IN (
  'Alpha Signals',
  'Nova Wallet',
  'TASKORA',
  'PayLink Africa',
  'Loop Studio',
  'Zenith Labs',
  'Aurum Wear'
);

-- Remove money that could only have been generated by the old demo/bonus flows.
-- Genuine task rewards are not touched.
DELETE FROM public.transactions
WHERE label IN ('Referral bonus', 'Welcome invite bonus')
   OR label LIKE 'Daily check-in — day %'
   OR label IN (
     'Verified — Alpha Signals',
     'Verified — Nova Wallet',
     'Verified — TASKORA',
     'Verified — PayLink Africa',
     'Verified — Loop Studio',
     'Verified — Zenith Labs',
     'Verified — Aurum Wear'
   );

-- Never expose exhausted tasks in marketplace queries.
CREATE INDEX IF NOT EXISTS tasks_active_slots_idx
  ON public.tasks(is_active, slots_left);
